export const layoutPolish = {
  name: 'layout-polish',
  enforce: 'pre' as const,
  transform(code:string,id:string){
    if(!id.endsWith('/src/phaser.css'))return null;
    return {code:code+`
html,body,.game-shell,.battlefield-viewport{overscroll-behavior:none;touch-action:none;-webkit-user-select:none;user-select:none;-webkit-touch-callout:none}
.piece-dragging,.piece-dragging body{overflow:hidden!important;overscroll-behavior:none!important;touch-action:none!important}
.drag-ghost{opacity:.42;filter:drop-shadow(0 0 7px rgba(109,224,255,.95))}.route-line{pointer-events:none;fill:none;stroke-linecap:round;stroke-linejoin:round}.route-outline{stroke:#f4fbff;stroke-width:19;filter:drop-shadow(0 0 4px rgba(63,197,255,.72))}.route-core{stroke:#41bfff;stroke-width:14}.route-outline.enemy{stroke:#fff0f0}.route-core.enemy{stroke:#ee5361}.route-head-outline{fill:#f4fbff;pointer-events:none;filter:drop-shadow(0 0 4px rgba(63,197,255,.72))}.route-head-core{fill:#41bfff;pointer-events:none}.route-head-outline.enemy{fill:#fff0f0}.route-head-core.enemy{fill:#ee5361}.spell-range{fill:#7b54c8;fill-opacity:.43;stroke:#d7b8ff;stroke-width:3;stroke-dasharray:7 5;vector-effect:non-scaling-stroke;pointer-events:none}
.hud-left,.hud-right{transform:translate3d(0,0,0);backface-visibility:hidden;will-change:transform;contain:layout paint}.game-board{overscroll-behavior:none;-webkit-user-select:none;user-select:none;-webkit-user-drag:none}.unit-token{touch-action:none;-webkit-user-select:none;user-select:none;-webkit-user-drag:none}
.route-outline{stroke:#f7fdff;stroke-width:18;filter:drop-shadow(0 0 5px rgba(48,190,255,.95))}.route-core{stroke:#35baff;stroke-width:12}.route-head-outline{fill:#f7fdff;filter:drop-shadow(0 0 5px rgba(48,190,255,.95))}.route-head-core{fill:#35baff}
.attack-intent-outline,.attack-intent-core{pointer-events:none;stroke-linecap:round}.attack-intent-outline{stroke:#fff4ed;stroke-width:12;filter:drop-shadow(0 0 5px rgba(255,39,55,.88))}.attack-intent-core{stroke:#b81526;stroke-width:7}.attack-intent-head-outline{fill:#fff4ed;pointer-events:none;filter:drop-shadow(0 0 5px rgba(255,39,55,.88))}.attack-intent-head-core{fill:#b81526;pointer-events:none}.attack-target-ring{fill:rgba(103,7,18,.2);stroke:#ff5360;stroke-width:3;stroke-dasharray:7 5;vector-effect:non-scaling-stroke;pointer-events:none;animation:intent-pulse .9s ease-in-out infinite alternate}.attack-damage-badge{pointer-events:none}.attack-damage-badge rect{fill:#7f101d;stroke:#fff3e7;stroke-width:2;vector-effect:non-scaling-stroke}.attack-damage-badge text{fill:#fff;font:900 15px/1 Inter,system-ui,sans-serif;paint-order:stroke;stroke:#3b050b;stroke-width:3}@keyframes intent-pulse{to{stroke:#fff1e8;fill:rgba(150,10,28,.34)}}
.combat-forecast{top:max(12px,env(safe-area-inset-top));bottom:auto;width:max-content;max-width:calc(100vw - 24px);grid-template-columns:26px auto;gap:1px 8px;padding:7px 12px 8px;border-width:1px;border-radius:999px;background:linear-gradient(180deg,rgba(91,22,30,.96),rgba(39,10,16,.97));box-shadow:0 7px 18px rgba(0,0,0,.48)}.combat-forecast>strong{grid-row:1/3;align-self:center;font-size:1.15rem}.combat-forecast>span{font:800 .76rem/1.1 Inter,system-ui,sans-serif;white-space:nowrap}.combat-forecast>b{font:900 .62rem/1.1 Inter,system-ui,sans-serif;letter-spacing:.06em;color:#ffd7d0;white-space:nowrap}
.action-bar{position:absolute;z-index:32;display:grid;gap:6px;width:92px;padding:7px;border:1px solid rgba(184,200,218,.62);border-radius:17px;background:linear-gradient(180deg,rgba(25,32,41,.96),rgba(6,10,15,.97));box-shadow:0 10px 24px rgba(0,0,0,.62),inset 0 1px 0 rgba(255,255,255,.1);pointer-events:auto;transform:none;transition:left .12s ease,top .12s ease}.action-bar:before{content:'';position:absolute;left:-7px;top:calc(50% - 7px);width:12px;height:12px;background:#121820;border-left:1px solid #8e9baa;border-bottom:1px solid #8e9baa;transform:rotate(45deg)}.action-bar.menu-left:before{left:auto;right:-7px;transform:rotate(225deg)}.action-bar[hidden]{display:none}.action-choice{position:relative;width:78px;height:42px;display:grid;grid-template-columns:27px 1fr;place-items:center;padding:4px 7px;border:1px solid #627080;border-radius:11px;color:#f4f7fa;background:linear-gradient(180deg,#343e49,#171d24);box-shadow:inset 0 1px 0 rgba(255,255,255,.1);touch-action:manipulation}.action-choice>span{font-size:1.15rem;line-height:1}.action-choice>b{justify-self:start;font:800 .67rem/1 Inter,system-ui,sans-serif;letter-spacing:.01em}.action-choice[aria-pressed="true"]{border-color:#f1bd69;color:#fff6dd;background:linear-gradient(180deg,#75442b,#361a19);box-shadow:0 0 0 2px rgba(241,189,105,.32),inset 0 1px 0 rgba(255,255,255,.12)}.action-choice:disabled{opacity:.38}
.combat-float{position:absolute;z-index:55;pointer-events:none;transform:translate(-50%,-100%);font:1000 1.45rem/1 Inter,system-ui,sans-serif;letter-spacing:-.04em;paint-order:stroke;filter:drop-shadow(0 3px 3px rgba(0,0,0,.9));animation:combat-float .86s cubic-bezier(.2,.75,.25,1) forwards}.combat-float.damage{color:#ff504f;-webkit-text-stroke:3px #4a080b}.combat-float.healing{color:#60e47a;-webkit-text-stroke:3px #083b16}@keyframes combat-float{0%{opacity:0;transform:translate(-50%,-78%) scale(.72)}18%{opacity:1;transform:translate(-50%,-120%) scale(1.12)}72%{opacity:1}100%{opacity:0;transform:translate(-50%,-230%) scale(1)}}
.initiative-dock{border-top:1px solid rgba(179,195,213,.42);background:linear-gradient(180deg,rgba(13,18,25,.62),rgba(4,7,11,.97) 35%);box-shadow:0 -12px 28px rgba(0,0,0,.32)}
.initiative-token{border-color:#c7d0db;box-shadow:0 5px 12px rgba(0,0,0,.78),inset 0 0 0 2px #131920,0 0 0 1px #6d7783}.initiative-token.enemy{border-color:#ff625f}.initiative-token.active{border-color:#eafaff;outline-color:#28aef8;box-shadow:0 0 20px rgba(40,174,248,.96),0 7px 14px rgba(0,0,0,.8)}
.hud-circle{position:relative;border-color:#aeb9c6;background:radial-gradient(circle at 35% 24%,#45505e 0,#252c35 43%,#090d12 100%);box-shadow:0 5px 13px rgba(0,0,0,.72),inset 0 0 0 3px #151b22,inset 0 2px 0 rgba(255,255,255,.18);font-family:Georgia,serif}
.utility-panel{display:grid;gap:10px;justify-items:center}.utility-panel[hidden]{display:none}.utility-toggle{font-size:1.7rem;line-height:1;transition:transform .18s ease,filter .18s ease}.utility-toggle.open{transform:rotate(180deg);filter:brightness(1.15)}.speech-icon{position:relative;display:block;width:22px;height:16px;border:2px solid currentColor;border-radius:6px}.speech-icon:after{content:'';position:absolute;left:3px;bottom:-6px;width:7px;height:7px;border-left:2px solid currentColor;border-bottom:2px solid currentColor;background:#202832;transform:skewY(-35deg)}.combat-log-panel{left:76px;right:auto}
.ability-menu-panel{width:min(286px,calc(100vw - 104px));padding:11px;border-color:#74808e;border-radius:16px;background:linear-gradient(180deg,rgba(32,38,47,.995),rgba(8,12,17,.995));box-shadow:0 16px 34px rgba(0,0,0,.72),inset 0 1px 0 rgba(255,255,255,.1)}.ability-menu-title{font:700 1.35rem/1.1 Georgia,serif}.ability-menu-panel button{border:2px solid #525d69;background:linear-gradient(180deg,#343b45,#181d24);box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 3px 7px rgba(0,0,0,.35)}.ability-menu-panel button strong{font:700 1.05rem Georgia,serif}.ability-menu-panel button b{border:1px solid #697482;box-shadow:inset 0 0 0 2px #090d12}.ability-icon{border:2px solid #87919d;box-shadow:inset 0 0 0 2px rgba(0,0,0,.35)}
:root{--c64-black:#000;--c64-white:#fff;--c64-red:#813338;--c64-cyan:#75cec8;--c64-purple:#8e3c97;--c64-green:#56ac4d;--c64-blue:#2e2c9b;--c64-yellow:#edf171;--c64-orange:#8e5029;--c64-brown:#553800;--c64-pink:#c46c71;--c64-dgray:#4a4a4a;--c64-gray:#7b7b7b;--c64-lgreen:#a9ff9f;--c64-lblue:#706deb;--c64-lgray:#b2b2b2}
html,body,button{font-family:"Courier New",ui-monospace,monospace}.game-shell,.battlefield-viewport{background:var(--c64-black)}button{-webkit-tap-highlight-color:transparent}.game-board,.battlefield-canvas{image-rendering:pixelated}
.route-outline{stroke:var(--c64-white);stroke-width:4;filter:none}.route-core{stroke:var(--c64-cyan);stroke-width:2}.route-head-outline{fill:var(--c64-white);filter:none}.route-head-core{fill:var(--c64-cyan)}.route-outline.enemy{stroke:var(--c64-pink)}.route-core.enemy,.route-head-core.enemy{stroke:var(--c64-red);fill:var(--c64-red)}
.hud-left,.hud-right{bottom:max(10px,env(safe-area-inset-bottom));gap:7px}.hud-right{right:10px;display:grid;justify-items:end}.hud-left{left:10px}.hud-circle{width:46px;height:46px;border:2px solid var(--c64-lgray);border-radius:0;color:var(--c64-white);background:var(--c64-blue);box-shadow:3px 3px 0 var(--c64-black),inset 2px 2px 0 var(--c64-lblue),inset -2px -2px 0 #171566;font:900 1.35rem/1 "Courier New",monospace}.hud-circle:active{transform:translate(2px,2px);box-shadow:1px 1px 0 var(--c64-black)}.action-toggle{color:#f7f9fc;background:linear-gradient(145deg,#68717b,#303840);font-size:1.5rem}.utility-toggle{display:grid;place-items:center;padding:0 0 3px;color:#f7f9fc;background:linear-gradient(145deg,#68717b,#303840);font-size:2.15rem;line-height:1}.utility-panel{gap:7px}
.action-bar{position:static!important;display:grid;width:108px;gap:4px;padding:5px;border:2px solid var(--c64-lgray);border-radius:0;background:var(--c64-black);box-shadow:3px 3px 0 var(--c64-black);transform:none;transition:none}.action-bar:before{display:none}.action-bar[hidden]{display:none}.action-choice{width:94px;height:36px;grid-template-columns:25px 1fr;padding:3px 6px;border:2px solid var(--c64-gray);border-radius:0;color:var(--c64-white);background:var(--c64-dgray);box-shadow:inset 1px 1px 0 var(--c64-lgray);font-family:"Courier New",monospace}.action-choice>span{font-size:1rem}.action-choice>b{font:900 .72rem/1 "Courier New",monospace;text-transform:uppercase}.action-choice[aria-pressed="true"]{border-color:var(--c64-yellow);color:var(--c64-yellow);background:var(--c64-red);box-shadow:none}.action-choice:disabled{opacity:.42;filter:saturate(.25)}
.initiative-dock{left:62px;right:62px;height:94px;border-top:2px solid var(--c64-gray);background:var(--c64-black);box-shadow:0 -3px 0 rgba(0,0,0,.7)}.initiative-rail{height:94px;gap:6px;padding:24px calc(50% - 23px) 8px;mask-image:linear-gradient(to right,transparent,#000 16%,#000 84%,transparent)}.initiative-token{flex-basis:46px;width:46px;height:46px;margin-bottom:15px;padding:2px;border:2px solid var(--c64-lgray);border-radius:0;color:var(--c64-white);background:var(--c64-dgray);box-shadow:2px 2px 0 var(--c64-black);transition:none}.initiative-token.enemy{border-color:var(--c64-pink);background:var(--c64-red)}.initiative-token.active{transform:translateY(-3px);border-color:var(--c64-yellow);outline:2px solid var(--c64-white);outline-offset:0;box-shadow:3px 4px 0 var(--c64-black)}.rail-sprite{display:block;width:38px;height:38px}.initiative-token small{top:calc(100% + 3px);max-width:64px;color:var(--c64-white);font:900 8px/1 "Courier New",monospace;text-shadow:1px 1px 0 var(--c64-black)}
.settings-popover,.combat-log-panel,.drawer-content{border:2px solid var(--c64-lgray);border-radius:0;background:var(--c64-black);box-shadow:4px 4px 0 var(--c64-black)}.settings-popover button,.mode-option,.combat-log-heading button{border:2px solid var(--c64-gray);border-radius:0;color:var(--c64-white);background:var(--c64-dgray)}.settings-popover .mode-option[aria-pressed="true"]{color:var(--c64-black);background:var(--c64-yellow)}.settings-label,.label,.stat-list dt{color:var(--c64-cyan)}.unit-drawer{width:220px}.drawer-content{background:var(--c64-blue)}.drawer-heading strong{color:var(--c64-yellow);text-transform:uppercase}.portrait{width:48px;height:48px;border:2px solid var(--c64-white);border-radius:0;background-color:var(--c64-dgray)!important}.stat-list div{border-color:var(--c64-lblue)}.combat-log-panel{background:var(--c64-black)}.log-entry{border-radius:0;background:var(--c64-dgray)}.log-entry b{color:var(--c64-yellow)}
.combat-float{font-family:"Courier New",monospace;filter:none;text-shadow:2px 2px 0 var(--c64-black)}.combat-float.damage{color:var(--c64-pink);-webkit-text-stroke:0}.combat-float.healing{color:var(--c64-lgreen);-webkit-text-stroke:0}.result-overlay{background:rgba(0,0,0,.92)}.result-overlay h2{font-family:"Courier New",monospace;color:var(--c64-yellow);text-transform:uppercase}.result-overlay button{border:2px solid var(--c64-white);border-radius:0;background:var(--c64-yellow);box-shadow:3px 3px 0 var(--c64-black);font-family:"Courier New",monospace}
@media (orientation:portrait){.battlefield-viewport{inset:0;height:100dvh;background:linear-gradient(#090d12,#020304)}.battlefield-frame{top:0!important;left:0!important;width:100%!important;height:auto!important;aspect-ratio:3/4;overflow:hidden;background:#000;transform:none!important}.battlefield{width:100%!important;height:100%!important;background:#000}.game-board{display:block;width:100%!important;height:100%!important;max-height:none!important;margin:0!important}.hud-left,.hud-right{bottom:max(12px,env(safe-area-inset-bottom))}}
@media (orientation:landscape){.battlefield-viewport{inset:0;padding-bottom:104px}.battlefield-frame{top:0;left:50%!important;right:auto;width:auto!important;height:calc(100dvh - 104px)!important;aspect-ratio:3/4;max-width:100vw;transform:translateX(-50%)}.battlefield{height:100%;width:100%}.game-board{height:100%!important;width:100%!important;max-height:calc(100dvh - 104px);max-width:100vw;margin:0 auto}.initiative-dock{top:auto!important;bottom:max(2px,env(safe-area-inset-bottom));left:20%!important;right:20%!important;height:94px}.initiative-rail{height:94px;padding-top:23px;padding-bottom:8px}.action-bar{bottom:auto!important}.hud-left,.hud-right{bottom:max(12px,env(safe-area-inset-bottom));gap:7px}.hud-left{left:max(12px,env(safe-area-inset-left));display:grid}.hud-right{right:max(12px,env(safe-area-inset-right));display:grid}.hud-circle{width:46px;height:46px}}
.action-toggle[hidden]{display:none!important}.initiative-token>.rail-sprite{position:absolute!important;inset:2px!important;width:auto!important;height:auto!important;border-radius:0!important}.battlefield-viewport{background:var(--c64-black)!important}.unit-token .token-outer{stroke-width:1}.token-glyph{font-size:9px}.obstacle>rect:first-child{fill:var(--c64-dgray);stroke:var(--c64-lgray);stroke-width:1}.obstacle-core{fill:var(--c64-black);stroke:var(--c64-gray);stroke-width:1}.obstacle text{fill:var(--c64-yellow);font:700 7px "Courier New",monospace}
html,body,button,.initiative-token small,.action-choice,.action-choice b,.combat-float,.result-overlay h2,.result-overlay button,.settings-popover,.combat-log-panel,.drawer-content{font-family:"IBM CGA","Courier New",monospace!important;font-synthesis:none}
html,body{font-size:16px;line-height:1.5;letter-spacing:0;background:#000}.battlefield-frame{border:4px solid var(--c64-white);box-shadow:0 0 0 4px var(--c64-blue)}
.hud-left,.hud-right{gap:8px;bottom:max(12px,env(safe-area-inset-bottom))}.hud-left{left:12px}.hud-right{right:12px}.hud-circle{width:60px;height:60px;border:4px solid var(--c64-white);background:var(--c64-blue);box-shadow:4px 4px 0 #000,inset 3px 3px 0 var(--c64-lblue),inset -3px -3px 0 #171566;font:400 24px/1 "IBM CGA",monospace!important}.hud-circle:active{transform:translate(3px,3px);box-shadow:1px 1px 0 #000}.action-toggle{background:var(--c64-red);color:var(--c64-yellow);font-size:28px!important}.utility-toggle{font-size:28px!important}.utility-panel{gap:8px}.speech-icon{width:28px;height:20px;border-width:3px;border-radius:0}.speech-icon:after{border-width:3px;background:var(--c64-blue)}
.action-bar{width:152px;gap:6px;padding:8px;border:4px double var(--c64-white);background:#000;box-shadow:5px 5px 0 #000}.action-choice{width:128px;height:52px;grid-template-columns:32px 1fr;padding:4px 8px;border:3px solid var(--c64-gray);background:var(--c64-dgray);box-shadow:inset 2px 2px 0 var(--c64-lgray);color:#fff}.action-choice>span{font-size:24px}.action-choice>b{font-size:16px;line-height:1;text-transform:uppercase;font-weight:400}.action-choice[aria-pressed="true"]{border-color:#fff;color:var(--c64-yellow);background:var(--c64-red);outline:2px solid var(--c64-yellow);outline-offset:-6px}
.initiative-dock{left:76px;right:76px;height:120px;border-top:4px double var(--c64-white);background:#000}.initiative-rail{height:120px;gap:8px;padding:28px calc(50% - 30px) 10px}.initiative-token{flex-basis:60px;width:60px;height:60px;margin-bottom:22px;padding:3px;border:3px solid var(--c64-lgray);background:#000;box-shadow:3px 3px 0 var(--c64-dgray)}.initiative-token.enemy{border-color:var(--c64-pink);background:#000}.initiative-token.active{transform:translateY(-5px);border-color:var(--c64-yellow);outline:3px solid #fff;box-shadow:4px 5px 0 var(--c64-blue)}.initiative-token>.rail-sprite{inset:3px!important}.initiative-token small{top:calc(100% + 5px);max-width:88px;font-size:16px;line-height:1;color:#fff;text-shadow:2px 2px 0 #000}
.settings-popover,.combat-log-panel,.drawer-content{border:4px double #fff;background:#000;box-shadow:6px 6px 0 var(--c64-blue);border-radius:0}.settings-popover{min-width:260px;padding:12px}.settings-label,.label{font-size:16px;color:var(--c64-cyan)}.settings-popover button,.mode-option{min-height:48px;padding:8px;border-width:3px;font-size:16px}.combat-log-panel{width:min(360px,calc(100vw - 96px));padding:12px}.combat-log-heading{font-size:24px}.combat-log-heading button{width:44px;height:44px;font-size:24px}.combat-log-list{gap:8px}.log-entry{grid-template-columns:48px 1fr;padding:10px;border:2px solid var(--c64-gray);background:#000}.log-entry b,.log-entry span{font-size:16px;line-height:1.25}.unit-drawer{width:min(280px,calc(100vw - 24px));top:max(12px,env(safe-area-inset-top));right:12px}.drawer-content{padding:16px;background:var(--c64-blue)}.drawer-heading{gap:12px;margin:12px 0 16px}.drawer-heading strong{font-size:24px;line-height:1}.portrait{width:72px;height:72px;border:4px solid #fff;background-color:#000!important}.stat-list div{padding:10px 0;border-top:2px solid var(--c64-lblue)}.stat-list dt,.stat-list dd{font-size:16px;line-height:1;margin:0}
.combat-float{font-size:24px;line-height:1;letter-spacing:0;text-shadow:3px 3px 0 #000}.result-overlay h2{font-size:40px;line-height:1}.result-overlay .eyebrow,.result-overlay p{font-size:16px}.result-overlay button{min-height:56px;padding:8px 16px;border:4px solid #fff;font-size:16px}.combat-forecast{border:3px solid #fff;border-radius:0;background:#000;box-shadow:4px 4px 0 var(--c64-red)}.combat-forecast>span,.combat-forecast>b{font-family:"IBM CGA",monospace!important;font-size:16px;line-height:1}.combat-forecast>strong{font-size:24px}
@media (orientation:portrait){.battlefield-frame{border-left:0;border-right:0}.initiative-dock{left:76px;right:76px;height:120px}.hud-circle{width:60px;height:60px}}
@media (orientation:landscape){.battlefield-viewport{padding-bottom:128px}.battlefield-frame{height:calc(100dvh - 128px)!important}.initiative-dock{height:116px;left:22%!important;right:22%!important}.initiative-rail{height:116px}.hud-circle{width:60px;height:60px}}
.drag-attack-cue{pointer-events:none;filter:drop-shadow(0 2px 2px rgba(0,0,0,.7))}.drag-attack-cue circle{fill:#fff8dc;stroke:#172a52;stroke-width:1.5}.drag-attack-cue text{fill:#c82f43;font:700 6px/1 Georgia,serif}.zoom-out-icon{position:relative;width:24px;height:24px;display:grid;place-items:center;border:3px solid currentColor;border-radius:50%;font:900 16px/14px system-ui}.zoom-out-icon:after{content:'';position:absolute;width:10px;height:3px;right:-7px;bottom:-3px;background:currentColor;transform:rotate(45deg);transform-origin:left center}
html:not([data-skin="classic"]),html:not([data-skin="classic"]) body,html:not([data-skin="classic"]) button,html:not([data-skin="classic"]) .initiative-token small,html:not([data-skin="classic"]) .action-choice,html:not([data-skin="classic"]) .action-choice b,html:not([data-skin="classic"]) .combat-float,html:not([data-skin="classic"]) .settings-popover,html:not([data-skin="classic"]) .combat-log-panel,html:not([data-skin="classic"]) .drawer-content{font-family:Georgia,"Times New Roman",serif!important;font-synthesis:auto}
html:not([data-skin="classic"]) body{font-size:15px;background:#111a2b}html:not([data-skin="classic"]) .battlefield-viewport{background:linear-gradient(#0c1728,#15243a)!important}html:not([data-skin="classic"]) .battlefield-frame{border:3px solid #e9d39a;box-shadow:0 0 0 3px #344f77,0 5px 18px rgba(0,0,0,.6)}
html:not([data-skin="classic"]) .hud-left,html:not([data-skin="classic"]) .hud-right{gap:8px;bottom:max(12px,env(safe-area-inset-bottom))}html:not([data-skin="classic"]) .hud-left{left:10px}html:not([data-skin="classic"]) .hud-right{right:10px}html:not([data-skin="classic"]) .hud-circle{width:56px;height:56px;border:3px solid #f3e4bc;border-radius:50%;color:#fff9e8;background:linear-gradient(145deg,#5e86ba 0,#294f86 45%,#142e59 100%);box-shadow:0 4px 0 #0c1830,inset 0 0 0 2px #83acd8,inset 0 2px 0 rgba(255,255,255,.55);font:700 23px/1 Georgia,serif!important}html:not([data-skin="classic"]) .hud-circle:active{transform:translateY(3px);box-shadow:0 1px 0 #0c1830}html:not([data-skin="classic"]) .action-toggle{color:#fff1c4;background:linear-gradient(145deg,#d35b61,#9f2437 52%,#58162a)}html:not([data-skin="classic"]) .utility-toggle{font-size:25px!important}html:not([data-skin="classic"]) .speech-icon:after{background:#294f86}
html:not([data-skin="classic"]) .action-bar{width:132px;gap:7px;padding:9px;border:3px solid #ead59a;border-radius:12px;background:linear-gradient(180deg,rgba(44,78,124,.98),rgba(16,38,75,.99));box-shadow:0 5px 0 #08162d,inset 0 0 0 2px #6f94c0}html:not([data-skin="classic"]) .action-choice{width:108px;height:48px;grid-template-columns:30px 1fr;padding:4px 8px;border:2px solid #d8c38e;border-radius:8px;color:#fff8e6;background:linear-gradient(#5f86b6,#315a91);box-shadow:inset 0 1px 0 rgba(255,255,255,.55),0 2px 0 #142c52}html:not([data-skin="classic"]) .action-choice>span{font-size:21px}html:not([data-skin="classic"]) .action-choice>b{font-size:14px;text-transform:none;font-weight:700}html:not([data-skin="classic"]) .action-choice[aria-pressed="true"]{color:#fff;background:linear-gradient(#d35c64,#93243c);border-color:#ffe4a3;outline:none}
html:not([data-skin="classic"]) .initiative-dock{left:68px;right:68px;height:104px;border-top:3px solid #d7be80;background:linear-gradient(180deg,rgba(21,41,70,.72),rgba(8,18,35,.98) 34%);box-shadow:0 -4px 0 rgba(9,20,40,.75)}html:not([data-skin="classic"]) .initiative-rail{height:104px;gap:7px;padding:27px calc(50% - 27px) 10px}html:not([data-skin="classic"]) .initiative-token{flex-basis:54px;width:54px;height:54px;margin-bottom:18px;padding:2px;border:3px solid #efe0b4;border-radius:50%;background:#172b4d;box-shadow:0 4px 0 #071327,inset 0 0 0 2px #547aa9}html:not([data-skin="classic"]) .initiative-token.enemy{border-color:#ef9b91;background:#58233a}html:not([data-skin="classic"]) .initiative-token.active{transform:translateY(-4px) scale(1.08);border-color:#fff2a8;outline:3px solid #5ed7ff;outline-offset:1px;box-shadow:0 0 14px rgba(63,199,255,.9),0 5px 0 #071327}html:not([data-skin="classic"]) .initiative-token>.rail-sprite{inset:2px!important;border-radius:50%!important}html:not([data-skin="classic"]) .initiative-token small{top:calc(100% + 4px);max-width:76px;color:#fff8e8;font-size:11px;line-height:1;text-shadow:0 2px 2px #000}
html:not([data-skin="classic"]) .settings-popover,html:not([data-skin="classic"]) .combat-log-panel,html:not([data-skin="classic"]) .drawer-content{border:3px solid #e2ca8d;border-radius:12px;background:linear-gradient(180deg,#345f96,#142e58);box-shadow:0 7px 0 #08162c,inset 0 0 0 2px #7296bd}html:not([data-skin="classic"]) .settings-popover{min-width:230px;padding:10px}html:not([data-skin="classic"]) .settings-label,html:not([data-skin="classic"]) .label{font-size:12px;color:#ffe9ad;letter-spacing:.08em}html:not([data-skin="classic"]) .settings-popover button,html:not([data-skin="classic"]) .mode-option{min-height:42px;border:2px solid #b9c8dc;border-radius:7px;color:#fff;background:linear-gradient(#4e75a5,#294e80);font-size:14px}html:not([data-skin="classic"]) .settings-popover .mode-option[aria-pressed="true"]{color:#24304a;background:linear-gradient(#fff4c8,#d9bd76);border-color:#fff3bb}html:not([data-skin="classic"]) .skin-options{margin-bottom:8px}
html:not([data-skin="classic"]) .unit-drawer{width:min(252px,calc(100vw - 20px))}html:not([data-skin="classic"]) .drawer-content{padding:13px}html:not([data-skin="classic"]) .portrait{width:58px;height:58px;border:3px solid #f1dfac;border-radius:50%;background-color:#142b50!important}html:not([data-skin="classic"]) .drawer-heading strong{font-size:20px;color:#fff3bd;text-transform:none}html:not([data-skin="classic"]) .stat-list div{padding:8px 0;border-color:rgba(232,215,168,.42)}html:not([data-skin="classic"]) .stat-list dt,html:not([data-skin="classic"]) .stat-list dd{font-size:13px}
html:not([data-skin="classic"]) .combat-float{font-family:Georgia,serif!important;font-size:25px;font-weight:900;text-shadow:0 2px 0 #000,2px 0 0 #000}html:not([data-skin="classic"]) .combat-forecast{border:2px solid #f2daa0;border-radius:18px;background:linear-gradient(#a83449,#651a31);box-shadow:0 4px 0 #351021}html:not([data-skin="classic"]) .combat-forecast>span,html:not([data-skin="classic"]) .combat-forecast>b{font-family:Georgia,serif!important;font-size:13px}
@media (orientation:portrait){html:not([data-skin="classic"]) .battlefield-frame{border-left:0;border-right:0}html:not([data-skin="classic"]) .initiative-dock{left:68px;right:68px;height:104px}}

.battlefield-canvas,.game-board{image-rendering:auto!important}
.drag-attack-cue circle{fill:#fff8e2;stroke:#183664;stroke-width:1.5}.drag-attack-cue text{fill:#b81f3e;font:700 6px/1 Georgia,serif}.drag-attack-cue.penalty circle{fill:#ffd59a;stroke:#8b3e27}.drag-attack-cue .penalty-note{fill:#fff;font:700 4px/1 system-ui,sans-serif;paint-order:stroke;stroke:#8b1f2c;stroke-width:2px}

.battlefield-frame{border:0!important;box-shadow:none!important}
.battlefield-viewport:after{content:'';position:absolute;z-index:20;left:0;right:0;bottom:0;height:104px;pointer-events:none;background:linear-gradient(180deg,rgba(6,14,28,.16) 0,rgba(5,13,28,.88) 22%,#030a17 100%);border-top:1px solid rgba(151,187,226,.32);box-shadow:0 -10px 24px rgba(1,7,17,.28)}
.initiative-dock,html:not([data-skin="classic"]) .initiative-dock{top:auto!important;bottom:0!important;left:70px!important;right:70px!important;height:96px!important;border:0!important;background:transparent!important;box-shadow:none!important}
.initiative-rail,html:not([data-skin="classic"]) .initiative-rail{height:96px!important;padding:16px calc(50% - 27px) 7px!important;gap:7px}
.initiative-token,html:not([data-skin="classic"]) .initiative-token{margin-bottom:18px}
.hud-left,.hud-right,html:not([data-skin="classic"]) .hud-left,html:not([data-skin="classic"]) .hud-right{bottom:max(13px,env(safe-area-inset-bottom))!important}
.action-dot{display:none!important}.action-bar[data-team="enemy"] .action-choice{opacity:.72}.action-bar[data-team="enemy"] .action-choice:not(:disabled){opacity:1}
.zoom-reset:disabled{opacity:.34}.zoom-reset:not(:disabled){opacity:1;filter:drop-shadow(0 0 5px rgba(82,196,255,.5))}
@media (orientation:portrait){.battlefield-frame{border:0!important}.initiative-dock,html:not([data-skin="classic"]) .initiative-dock{left:70px!important;right:70px!important;height:96px!important}}

/* FE-style board feedback: quiet selection frame and one continuous route ribbon. */
.action-bar .action-choice[hidden]{display:none!important}
.route-line{fill:none;stroke-linecap:round;stroke-linejoin:round;pointer-events:none}
.route-outline{stroke:rgba(226,252,255,.96)!important;stroke-width:5.8!important;filter:drop-shadow(0 0 2px rgba(42,205,244,.9))!important}
.route-core{stroke:rgba(50,196,235,.76)!important;stroke-width:4.15!important}
.route-shine{stroke:rgba(255,255,255,.82);stroke-width:.7;fill:none;pointer-events:none}
.route-head-outline{fill:rgba(226,252,255,.98)!important;filter:drop-shadow(0 0 2px rgba(42,205,244,.9))!important}
.route-head-core{fill:rgba(50,196,235,.86)!important}
.route-outline.enemy{stroke:rgba(255,235,232,.96)!important}.route-core.enemy{stroke:rgba(230,70,82,.82)!important}.route-shine.enemy{stroke:rgba(255,232,226,.72)}.route-head-outline.enemy{fill:rgba(255,235,232,.98)!important}.route-head-core.enemy{fill:rgba(230,70,82,.9)!important}

/* Single translucent route ribbon: isolated v2 classes avoid legacy vector artefacts. */
.route-border-v2,.route-ribbon-v2{fill:none;stroke-linecap:round;stroke-linejoin:round;pointer-events:none}
.route-border-v2{stroke:rgba(18,73,132,.42);stroke-width:5.5;filter:drop-shadow(0 0 1.5px rgba(30,188,229,.42))}
.route-ribbon-v2{stroke:rgba(51,196,232,.64);stroke-width:4}
.route-head-v2{fill:rgba(51,196,232,.68);stroke:rgba(191,246,255,.72);stroke-width:.65;stroke-linejoin:round;pointer-events:none;filter:drop-shadow(0 0 1px rgba(30,188,229,.4))}
.route-border-v2.enemy{stroke:rgba(116,33,53,.38)}.route-ribbon-v2.enemy{stroke:rgba(225,70,84,.6)}.route-head-v2.enemy{fill:rgba(225,70,84,.66);stroke:rgba(255,213,207,.65)}

/* Final FE UI refinements. Keep these last so legacy skin rules cannot win. */
.hud-icon{width:27px;height:27px;display:block;overflow:visible;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.menu-icon circle{fill:currentColor;stroke:none}
.action-toggle,.utility-toggle,html:not([data-skin="classic"]) .action-toggle,html:not([data-skin="classic"]) .utility-toggle{color:#f5fbff!important;background:linear-gradient(145deg,#5f91c9 0,#32669f 48%,#1d477b 100%)!important;border:0!important;box-shadow:0 4px 10px rgba(4,16,34,.58)!important}
.hud-left,.hud-right,html:not([data-skin="classic"]) .hud-left,html:not([data-skin="classic"]) .hud-right{bottom:max(24px,env(safe-area-inset-bottom))!important}.chevron-icon{display:block;font:700 34px/1 Georgia,serif;transform:translateY(1px)}
.action-toggle{font-size:0!important}.unit-drawer[data-team="enemy"] .drawer-content{background:linear-gradient(180deg,#8f3444,#421827)!important;border-color:#efb2a9!important;box-shadow:0 7px 0 #260b14,inset 0 0 0 2px #bc6370!important}.unit-drawer[data-team="enemy"] .portrait{background-color:#4b1725!important;border-color:#ffd2c7!important}.unit-drawer[data-team="enemy"] .label{color:#ffd0c7!important}
.action-symbol{display:grid!important;place-items:center;font-family:Arial,sans-serif!important;font-size:24px!important;font-weight:500!important;line-height:1!important}.action-symbol svg{width:24px;height:24px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
.initiative-rail,html:not([data-skin="classic"]) .initiative-rail{height:104px!important;padding:7px calc(50% - 32px) 3px!important;gap:8px!important}.initiative-token,html:not([data-skin="classic"]) .initiative-token{flex-basis:64px!important;width:64px!important;height:64px!important;margin-bottom:19px!important}.initiative-token>.rail-sprite,html:not([data-skin="classic"]) .initiative-token>.rail-sprite{inset:2px!important}.initiative-token small{display:none!important}.initiative-token.selected small{display:block!important;top:calc(100% + 4px)!important;max-width:92px!important;font-size:11px!important;line-height:1!important}
.action-bar[data-team="enemy"] .action-choice.enemy-choice{opacity:1!important;transform:translateY(2px) scale(.98);color:#fff!important;background:linear-gradient(#da6a70,#8e263b)!important;border-color:#ffe09b!important;box-shadow:0 0 0 3px rgba(255,214,127,.28),inset 0 2px 4px rgba(39,5,12,.45)!important;filter:brightness(1.16)}
.attack-action-cue>circle{fill:#f5edcf;stroke:none;filter:drop-shadow(0 1px 1px rgba(21,8,11,.42))}.attack-cue-icon path,.attack-cue-icon rect,.attack-cue-icon circle{fill:#bd2940;stroke:none}.attack-action-cue.melee .attack-cue-icon{transform:scale(.64);transform-box:fill-box;transform-origin:center}.attack-action-cue.ranged .attack-cue-icon{transform:scale(.76);transform-box:fill-box;transform-origin:center}
.initiative-token.player:not(.active),html:not([data-skin="classic"]) .initiative-token.player:not(.active){border-color:#aeb6bf!important;background:#2d3640!important;box-shadow:0 4px 0 #0b1118,inset 0 0 0 2px #69737e!important}.initiative-token.player.active,html:not([data-skin="classic"]) .initiative-token.player.active{border-color:#61c9f3!important;outline-color:#217fbd!important;box-shadow:0 0 14px rgba(58,180,235,.82),0 5px 0 #071327!important}

`,map:null};
  }
};
