/* Classes from Player's Handbook 1 and 2, plus a custom class for anything else.
   Summaries written for this app. Class feature powers are defined at the bottom. */
'use strict';

const SIMPLE_MELEE = 'simple-melee', MILITARY_MELEE = 'military-melee', SIMPLE_RANGED = 'simple-ranged', MILITARY_RANGED = 'military-ranged';

D4.classes = {
  cleric: {
    name: 'Cleric', src: 'PHB', role: 'Leader', source: 'Divine', key: ['wis', 'str', 'cha'],
    desc: 'A battle priest who heals allies, grants them bonuses and smites foes with holy power. Clerics use Wisdom for ranged prayers and Strength for melee prayers.',
    armor: ['cloth', 'leather', 'hide', 'chainmail'], shields: [],
    weapons: [SIMPLE_MELEE, SIMPLE_RANGED], implements: ['Holy symbol'],
    def: { Will: 2 }, hp1: 12, hpLvl: 5, surges: 7,
    skills: { fixed: ['religion'], choose: 3, list: ['arcana', 'diplomacy', 'heal', 'history', 'insight', 'religion'] },
    builds: {
      battle: { name: 'Battle Cleric', abil: 'Strength, Wisdom, Charisma', desc: 'Wades into melee with weapon prayers. Feats: Weapon Focus, Healing Hands.' },
      devoted: { name: 'Devoted Cleric', abil: 'Wisdom, Charisma, Strength', desc: 'Stays back with ranged prayers and focuses on healing and buffs. Feat: Healing Hands.' },
    },
    features: [
      { name: 'Channel Divinity', desc: 'Once per encounter you can use one Channel Divinity power. Every cleric has divine fortune and turn undead; some feats give more options.' },
      { name: 'Healer\'s Lore', desc: 'When you grant healing with a cleric power that has the Healing keyword, add your Wisdom modifier to the hit points the target regains.' },
      { name: 'Healing Word', desc: 'You can use the healing word power twice per encounter (three times from 16th level).' },
      { name: 'Ritual Casting', desc: 'You gain Ritual Caster as a bonus feat. Your ritual book holds Gentle Repose and one other 1st-level ritual.' },
    ],
    powers: ['cleric-healing-word', 'cleric-divine-fortune', 'cleric-turn-undead'],
    bonusFeats: ['ritual-caster'],
  },
  fighter: {
    name: 'Fighter', src: 'PHB', role: 'Defender', source: 'Martial', key: ['str', 'con', 'dex', 'wis'],
    desc: 'A master of weapons and armor who locks down enemies, punishes them for attacking allies and keeps them from getting past. Strength drives your attacks; Wisdom improves your opportunity attacks.',
    armor: ['cloth', 'leather', 'hide', 'chainmail', 'scale'], shields: ['light', 'heavy'],
    weapons: [SIMPLE_MELEE, MILITARY_MELEE, SIMPLE_RANGED, MILITARY_RANGED], implements: [],
    def: { Fort: 2 }, hp1: 15, hpLvl: 6, surges: 9,
    skills: { choose: 3, list: ['athletics', 'endurance', 'heal', 'intimidate', 'streetwise'] },
    builds: {
      great: { name: 'Great Weapon Fighter', abil: 'Strength, Constitution, Wisdom', desc: 'Big two-handed weapon, big damage. Feat: Power Attack.' },
      guardian: { name: 'Guardian Fighter', abil: 'Strength, Dexterity, Wisdom', desc: 'One-handed weapon and a shield, great defenses. Feat: Toughness.' },
    },
    features: [
      { name: 'Combat Challenge', desc: 'Whenever you attack an enemy, hit or miss, you can mark it until the end of your next turn. A marked enemy takes -2 to attacks that don\'t include you. If a marked enemy adjacent to you shifts or makes an attack that doesn\'t include you, you can make a melee basic attack against it as an immediate interrupt.' },
      { name: 'Combat Superiority', desc: 'You add your Wisdom modifier to opportunity attack rolls. An enemy you hit with an opportunity attack stops moving if its movement provoked the attack (it can use remaining actions to move again).' },
      { name: 'Fighter Weapon Talent', desc: 'Choose one-handed or two-handed weapons. You gain a +1 bonus to attack rolls with weapons of that kind.' },
    ],
    options: [{ id: 'talent', label: 'Fighter Weapon Talent', opts: {
      one: { name: 'One-handed weapons', desc: '+1 to attack rolls with one-handed weapons. Pairs well with a shield (Guardian Fighter).' },
      two: { name: 'Two-handed weapons', desc: '+1 to attack rolls with two-handed weapons (Great Weapon Fighter).' },
    } }],
    powers: ['fighter-combat-challenge'],
  },
  paladin: {
    name: 'Paladin', src: 'PHB', role: 'Defender', source: 'Divine', key: ['str', 'cha', 'wis'],
    desc: 'A holy warrior in heavy armor who challenges foes to fight them and burns them with radiant damage if they attack anyone else. Paladins can also heal with a touch.',
    armor: ['cloth', 'leather', 'hide', 'chainmail', 'scale', 'plate'], shields: ['light', 'heavy'],
    weapons: [SIMPLE_MELEE, MILITARY_MELEE, SIMPLE_RANGED], implements: ['Holy symbol'],
    def: { Fort: 1, Ref: 1, Will: 1 }, hp1: 15, hpLvl: 6, surges: 10,
    skills: { fixed: ['religion'], choose: 3, list: ['diplomacy', 'endurance', 'heal', 'history', 'insight', 'intimidate', 'religion'] },
    builds: {
      avenging: { name: 'Avenging Paladin', abil: 'Strength, Wisdom, Charisma', desc: 'Strength-based strikes that hit hard. Feat: Weapon Focus.' },
      protecting: { name: 'Protecting Paladin', abil: 'Charisma, Wisdom, Strength', desc: 'Charisma-based powers that heal and protect allies. Feat: Healing Hands.' },
    },
    features: [
      { name: 'Channel Divinity', desc: 'Once per encounter you can use one Channel Divinity power. Every paladin has divine mettle and divine strength.' },
      { name: 'Divine Challenge', desc: 'You can mark an enemy with the divine challenge power. If it attacks anyone but you, it takes radiant damage.' },
      { name: 'Lay on Hands', desc: 'You can use the lay on hands power a number of times per day equal to your Wisdom modifier (minimum 1), spending your own healing surges to heal others.' },
    ],
    powers: ['paladin-divine-challenge', 'paladin-lay-on-hands', 'paladin-divine-mettle', 'paladin-divine-strength'],
  },
  ranger: {
    name: 'Ranger', src: 'PHB', role: 'Striker', source: 'Martial', key: ['str', 'dex', 'wis'],
    desc: 'A hunter who picks out one enemy as quarry and brings it down with two blades or a bow. Rangers attack twice with twin strike and deal extra damage to their quarry.',
    armor: ['cloth', 'leather', 'hide'], shields: [],
    weapons: [SIMPLE_MELEE, MILITARY_MELEE, SIMPLE_RANGED, MILITARY_RANGED], implements: [],
    def: { Fort: 1, Ref: 1 }, hp1: 12, hpLvl: 5, surges: 6,
    skills: { oneOf: ['dungeoneering', 'nature'], choose: 4, list: ['acrobatics', 'athletics', 'dungeoneering', 'endurance', 'heal', 'nature', 'perception', 'stealth'] },
    builds: {
      archer: { name: 'Archer Ranger', abil: 'Dexterity, Wisdom, Strength', desc: 'Longbow from range. Feat: Lethal Hunter.' },
      twoblade: { name: 'Two-Blade Ranger', abil: 'Strength, Dexterity, Wisdom', desc: 'A weapon in each hand. Feat: Lethal Hunter.' },
    },
    features: [
      { name: 'Fighting Style', desc: 'Archer: you gain Defensive Mobility as a bonus feat. Two-Blade: you can wield a one-handed weapon in your off hand as if it were an off-hand weapon, and you gain Toughness as a bonus feat.' },
      { name: 'Hunter\'s Quarry', desc: 'You can use the hunter\'s quarry power to deal extra damage to one enemy once per round.' },
      { name: 'Prime Shot', desc: 'If none of your allies are nearer to your target than you are, you gain a +1 bonus to ranged attack rolls against that target.' },
    ],
    options: [{ id: 'style', label: 'Fighting Style', opts: {
      archer: { name: 'Archer', desc: 'Bonus feat: Defensive Mobility (+2 AC against opportunity attacks).' },
      twoblade: { name: 'Two-Blade', desc: 'Wield a one-handed weapon in your off hand. Bonus feat: Toughness (+5 hit points per tier).' },
    } }],
    powers: ['ranger-hunters-quarry'],
    mods: [['atk.ranged', 1, 'untyped', 'Prime Shot: when no ally is nearer the target']],
  },
  rogue: {
    name: 'Rogue', src: 'PHB', role: 'Striker', source: 'Martial', key: ['dex', 'str', 'cha'],
    desc: 'A quick, sly fighter who gets combat advantage and turns it into big Sneak Attack damage. Rogues use light blades, crossbows and slings.',
    armor: ['cloth', 'leather'], shields: [],
    weapons: ['dagger', 'hand-crossbow', 'shuriken', 'sling', 'short-sword'], implements: [],
    def: { Ref: 2 }, hp1: 12, hpLvl: 5, surges: 6,
    skills: { fixed: ['stealth', 'thievery'], choose: 4, list: ['acrobatics', 'athletics', 'bluff', 'dungeoneering', 'insight', 'intimidate', 'perception', 'stealth', 'streetwise', 'thievery'] },
    builds: {
      brawny: { name: 'Brawny Rogue', abil: 'Dexterity, Strength, Charisma', desc: 'Brutal Scoundrel tactics for extra Sneak Attack damage. Feat: Weapon Focus.' },
      trickster: { name: 'Trickster Rogue', abil: 'Dexterity, Charisma, Strength', desc: 'Artful Dodger tactics; tricks and misdirection. Feat: Backstabber.' },
    },
    features: [
      { name: 'First Strike', desc: 'At the start of an encounter, you have combat advantage against any creature that has not yet acted in that encounter.' },
      { name: 'Rogue Tactics', desc: 'Artful Dodger: +Charisma modifier to AC against opportunity attacks. Brutal Scoundrel: add your Strength modifier to Sneak Attack damage.' },
      { name: 'Rogue Weapon Talent', desc: 'Your shuriken damage die increases by one size (d4 to d6), and you gain a +1 bonus to attack rolls with daggers.' },
      { name: 'Sneak Attack', desc: 'Once per round, when you have combat advantage against an enemy and hit it with a light blade, crossbow or sling, you deal extra damage: 2d6 (3d6 at 11th level, 5d6 at 21st level).' },
    ],
    options: [{ id: 'tactics', label: 'Rogue Tactics', opts: {
      artful: { name: 'Artful Dodger', desc: 'Bonus to AC against opportunity attacks equal to your Charisma modifier. Some powers get better with Charisma.' },
      brutal: { name: 'Brutal Scoundrel', desc: 'Add your Strength modifier to Sneak Attack damage. Some powers get better with Strength.' },
    } }],
    powers: ['rogue-sneak-attack'],
  },
  warlock: {
    name: 'Warlock', src: 'PHB', role: 'Striker', source: 'Arcane', key: ['cha', 'con', 'int'],
    desc: 'A spellcaster who made a pact with a mysterious power. Warlocks curse enemies for extra damage and blast them with eldritch energy, using Charisma or Constitution.',
    armor: ['cloth', 'leather'], shields: [],
    weapons: [SIMPLE_MELEE, SIMPLE_RANGED], implements: ['Rod', 'Wand'],
    def: { Ref: 1, Will: 1 }, hp1: 12, hpLvl: 5, surges: 6,
    skills: { choose: 4, list: ['arcana', 'bluff', 'history', 'insight', 'intimidate', 'religion', 'streetwise', 'thievery'] },
    builds: {
      deceptive: { name: 'Deceptive Warlock', abil: 'Charisma, Intelligence, Constitution', desc: 'Fey or star pact spells that trick and misdirect. Feat: Improved Misty Step or Improved Fate of the Void.' },
      scourge: { name: 'Scourge Warlock', abil: 'Constitution, Intelligence, Charisma', desc: 'Infernal pact spells that deal damage and punish attackers. Feat: Improved Dark One\'s Blessing.' },
    },
    features: [
      { name: 'Eldritch Blast', desc: 'Every warlock knows the eldritch blast at-will power. It can be used as a ranged basic attack.' },
      { name: 'Eldritch Pact', desc: 'You choose a pact: fey, infernal or star. It gives you an extra at-will power and a pact boon that triggers when your cursed enemies drop.' },
      { name: 'Prime Shot', desc: 'If none of your allies are nearer to your target than you are, you gain a +1 bonus to ranged attack rolls against that target.' },
      { name: 'Shadow Walk', desc: 'On your turn, if you move at least 3 squares away from where you started your turn, you gain concealment until the end of your next turn.' },
      { name: 'Warlock\'s Curse', desc: 'Curse the nearest enemy as a minor action; once per round you deal extra damage to a cursed enemy you damage: 1d6 (2d6 at 11th level, 3d6 at 21st level).' },
    ],
    options: [{ id: 'pact', label: 'Eldritch Pact', opts: {
      fey: { name: 'Fey Pact', desc: 'At-will: eyebite. Boon (Misty Step): when an enemy under your curse drops to 0 hit points, you can teleport 3 squares as a free action. Pact spells favor Charisma.' },
      infernal: { name: 'Infernal Pact', desc: 'At-will: hellish rebuke. Boon (Dark One\'s Blessing): when an enemy under your curse drops to 0 hit points, you gain temporary hit points equal to your level. Pact spells favor Constitution.' },
      star: { name: 'Star Pact', desc: 'At-will: dire radiance. Boon (Fate of the Void): when an enemy under your curse drops to 0 hit points, you gain +1 to a single d20 roll during your next turn (cumulative). Pact spells favor Charisma.' },
    } }],
    powers: ['warlock-eldritch-blast', 'warlock-warlocks-curse'],
    optPowers: { pact: { fey: ['warlock-eyebite'], infernal: ['warlock-hellish-rebuke'], star: ['warlock-dire-radiance'] } },
    atWillSlots: 0, // eldritch blast and the pact at-will fill both at-will picks
    mods: [['atk.ranged', 1, 'untyped', 'Prime Shot: when no ally is nearer the target']],
  },
  warlord: {
    name: 'Warlord', src: 'PHB', role: 'Leader', source: 'Martial', key: ['str', 'int', 'cha'],
    desc: 'A battlefield commander who fights in the front line and directs allies: granting them attacks, moving them around and healing with inspiring words.',
    armor: ['cloth', 'leather', 'hide', 'chainmail'], shields: ['light'],
    weapons: [SIMPLE_MELEE, MILITARY_MELEE, SIMPLE_RANGED], implements: [],
    def: { Fort: 1, Will: 1 }, hp1: 12, hpLvl: 5, surges: 7,
    skills: { choose: 4, list: ['athletics', 'diplomacy', 'endurance', 'heal', 'history', 'intimidate'] },
    builds: {
      inspiring: { name: 'Inspiring Warlord', abil: 'Strength, Charisma, Intelligence', desc: 'Heals and bolsters allies. Feat: Inspired Recovery.' },
      tactical: { name: 'Tactical Warlord', abil: 'Strength, Intelligence, Charisma', desc: 'Grants attacks and positions allies. Feat: Tactical Assault.' },
    },
    features: [
      { name: 'Combat Leader', desc: 'You and each ally within 10 squares who can see and hear you gain a +2 power bonus to initiative.' },
      { name: 'Commanding Presence', desc: 'Inspiring Presence: when an ally who can see you spends an action point to take an extra action, the ally also regains hit points equal to one-half your level + your Charisma modifier. Tactical Presence: when an ally you can see spends an action point to make an extra attack, the ally gains a bonus to that attack roll equal to one-half your Intelligence modifier.' },
      { name: 'Inspiring Word', desc: 'You can use the inspiring word power twice per encounter (three times from 16th level).' },
    ],
    options: [{ id: 'presence', label: 'Commanding Presence', opts: {
      inspiring: { name: 'Inspiring Presence', desc: 'Allies who spend an action point also regain hit points (one-half your level + Charisma modifier).' },
      tactical: { name: 'Tactical Presence', desc: 'Allies who spend an action point to attack gain one-half your Intelligence modifier to the attack roll.' },
    } }],
    powers: ['warlord-inspiring-word'],
    mods: [['init', 2, 'power', null]],
  },
  wizard: {
    name: 'Wizard', src: 'PHB', role: 'Controller', source: 'Arcane', key: ['int', 'wis', 'dex'],
    desc: 'A scholar of arcane magic who hits many enemies at once with bursts and blasts and shapes the battlefield with zones and conditions. Intelligence powers every spell.',
    armor: ['cloth'], shields: [],
    weapons: ['dagger', 'quarterstaff'], implements: ['Orb', 'Staff', 'Wand'],
    def: { Will: 2 }, hp1: 10, hpLvl: 4, surges: 6,
    skills: { fixed: ['arcana'], choose: 3, list: ['arcana', 'diplomacy', 'dungeoneering', 'history', 'insight', 'nature', 'religion'] },
    builds: {
      control: { name: 'Control Wizard', abil: 'Intelligence, Wisdom, Dexterity', desc: 'Hinders and disables enemies. Orb of Imposition. Feat: Improved Initiative.' },
      war: { name: 'War Wizard', abil: 'Intelligence, Dexterity, Wisdom', desc: 'Maximum area damage. Wand of Accuracy. Feat: Improved Initiative.' },
    },
    features: [
      { name: 'Arcane Implement Mastery', desc: 'Choose an implement: Orb of Imposition, Staff of Defense or Wand of Accuracy. You must be wielding that implement to use its benefit.' },
      { name: 'Cantrips', desc: 'You know the ghost sound, light, mage hand and prestidigitation at-will utility spells.' },
      { name: 'Ritual Casting', desc: 'You gain Ritual Caster as a bonus feat. Your spellbook holds three 1st-level rituals.' },
      { name: 'Spellbook', desc: 'Your spellbook holds two daily attack spells and two utility spells of each level you know. After an extended rest you prepare one of each level to use that day.' },
    ],
    options: [{ id: 'implement', label: 'Arcane Implement Mastery', opts: {
      orb: { name: 'Orb of Imposition', desc: 'Once per encounter (free action): one target of your wizard power takes a penalty equal to your Wisdom modifier to its first saving throw against it, or extend an at-will spell effect that would end this turn until the end of your next turn.' },
      staff: { name: 'Staff of Defense', desc: '+1 bonus to AC while you wield a staff. Once per encounter, as an immediate interrupt, add your Constitution modifier to one defense against one attack.' },
      wand: { name: 'Wand of Accuracy', desc: 'Once per encounter (free action), add your Dexterity modifier to one attack roll.' },
    } }],
    powers: ['wizard-ghost-sound', 'wizard-light', 'wizard-mage-hand', 'wizard-prestidigitation'],
    bonusFeats: ['ritual-caster'],
    spellbook: true,
  },

  /* Player's Handbook 2 */
  avenger: {
    name: 'Avenger', src: 'PHB2', role: 'Striker', source: 'Divine', key: ['wis', 'dex', 'int'],
    desc: 'A divine assassin in light robes who swears an oath of enmity against one foe and hunts it down, rolling twice when fighting it alone.',
    armor: ['cloth'], shields: [], weapons: [SIMPLE_MELEE, MILITARY_MELEE, SIMPLE_RANGED], implements: ['Holy symbol'],
    def: { Fort: 1, Ref: 1, Will: 1 }, hp1: 14, hpLvl: 6, surges: 7,
    skills: { fixed: ['religion'], choose: 3, list: ['acrobatics', 'athletics', 'endurance', 'heal', 'intimidate', 'perception', 'religion', 'stealth', 'streetwise'] },
    features: [
      { name: 'Armor of Faith', desc: 'While you wear cloth armor or no armor and don\'t use a heavy shield, you gain a +3 bonus to AC.' },
      { name: 'Avenger\'s Censure', desc: 'Censure of Pursuit rewards you for chasing your oath target when it moves away (extra damage based on Dexterity). Censure of Retribution rewards you when other enemies hit you (extra damage against your oath target based on Intelligence).' },
      { name: 'Channel Divinity', desc: 'Once per encounter you can use one Channel Divinity power, such as abjure undead or divine guidance.' },
      { name: 'Oath of Enmity', desc: 'Encounter, minor action: choose an enemy within 10 squares. When you make a melee attack against it while it is the only enemy adjacent to you, roll twice and use either result.' },
    ],
    options: [{ id: 'censure', label: 'Avenger\'s Censure', opts: { pursuit: { name: 'Censure of Pursuit', desc: 'Favors Dexterity. Bonus damage when your oath target moves away from you.' }, retribution: { name: 'Censure of Retribution', desc: 'Favors Intelligence. Bonus damage against your oath target when other enemies hit you.' } } }],
    mods: [['AC', 3, 'untyped', null, c => c.armorWeight !== 'heavy' && (!c.armor || c.armor.type === 'cloth') && !(c.shield && c.shield.heavy)]],
  },
  barbarian: {
    name: 'Barbarian', src: 'PHB2', role: 'Striker', source: 'Primal', key: ['str', 'con', 'cha'],
    desc: 'A savage warrior who channels primal spirits into rage, hitting with huge two-handed weapons and chaining critical hits.',
    armor: ['cloth', 'leather', 'hide'], shields: [], weapons: [SIMPLE_MELEE, MILITARY_MELEE], implements: [],
    def: { Fort: 2 }, hp1: 15, hpLvl: 6, surges: 8,
    skills: { choose: 3, list: ['acrobatics', 'athletics', 'endurance', 'heal', 'intimidate', 'nature', 'perception'] },
    features: [
      { name: 'Barbarian Agility', desc: 'While you are not wearing heavy armor, you gain a +1 bonus to AC and Reflex (+2 at 11th level, +3 at 21st level).' },
      { name: 'Feral Might', desc: 'Rageblood Vigor (Constitution): gain temporary hit points when you drop enemies. Thaneborn Triumph (Charisma): gain benefits when you bloody enemies.' },
      { name: 'Rage Strike', desc: 'While raging, you can expend an unused daily rage power to make a rage strike, a big melee attack.' },
      { name: 'Rampage', desc: 'Once per round, when you score a critical hit with a barbarian attack power, you can make a melee basic attack as a free action.' },
    ],
    options: [{ id: 'might', label: 'Feral Might', opts: { rageblood: { name: 'Rageblood Vigor', desc: 'Favors Constitution. Temporary hit points when you drop enemies.' }, thaneborn: { name: 'Thaneborn Triumph', desc: 'Favors Charisma. Rewards you for bloodying enemies.' } } }],
    mods: [['AC', c => c.tier, 'untyped', null, c => c.armorWeight !== 'heavy'], ['Ref', c => c.tier, 'untyped', null, c => c.armorWeight !== 'heavy']],
  },
  bard: {
    name: 'Bard', src: 'PHB2', role: 'Leader', source: 'Arcane', key: ['cha', 'con', 'int'],
    desc: 'An arcane performer whose songs and words heal, inspire and reposition allies. Bards are skilled at everything and can dabble in other classes.',
    armor: ['cloth', 'leather', 'hide', 'chainmail'], shields: ['light'],
    weapons: [SIMPLE_MELEE, 'longsword', 'scimitar', 'short-sword', SIMPLE_RANGED, MILITARY_RANGED], implements: ['Wand'],
    def: { Ref: 1, Will: 1 }, hp1: 12, hpLvl: 5, surges: 7,
    skills: { fixed: ['arcana'], choose: 4, list: ['acrobatics', 'arcana', 'athletics', 'bluff', 'diplomacy', 'dungeoneering', 'heal', 'history', 'insight', 'intimidate', 'nature', 'perception', 'religion', 'streetwise'] },
    features: [
      { name: 'Bardic Training', desc: 'You gain Ritual Caster as a bonus feat and know some rituals.' },
      { name: 'Bardic Virtue', desc: 'Virtue of Cunning lets you move allies out of danger when attacks miss them. Virtue of Valor grants temporary hit points to allies who bloody or drop enemies.' },
      { name: 'Majestic Word', desc: 'Twice per encounter (three times from 16th level), a minor action lets you or an ally spend a healing surge and regain extra hit points.' },
      { name: 'Multiclass Versatility', desc: 'You can take multiclass feats for more than one class.' },
      { name: 'Skill Versatility', desc: 'You gain a +1 bonus to untrained skill checks.' },
      { name: 'Song of Rest', desc: 'When you play or sing during a short rest, allies who spend healing surges regain extra hit points equal to your Charisma modifier.' },
      { name: 'Words of Friendship', desc: 'Once per encounter, a minor action gives you a +5 bonus to your next Diplomacy check.' },
    ],
    options: [{ id: 'virtue', label: 'Bardic Virtue', opts: { cunning: { name: 'Virtue of Cunning', desc: 'Favors Intelligence. Slide allies out of harm.' }, valor: { name: 'Virtue of Valor', desc: 'Favors Constitution. Temporary hit points for allies.' } } }],
    bonusFeats: ['ritual-caster'],
    mods: [['untrained', 1, 'untyped']],
  },
  druid: {
    name: 'Druid', src: 'PHB2', role: 'Controller', source: 'Primal', key: ['wis', 'con', 'dex'],
    desc: 'A shapechanger who calls on nature\'s fury, switching between beast form for melee and humanoid form for primal spells.',
    armor: ['cloth', 'leather', 'hide'], shields: [], weapons: [SIMPLE_MELEE, SIMPLE_RANGED], implements: ['Staff', 'Totem'],
    def: { Ref: 1, Will: 1 }, hp1: 12, hpLvl: 5, surges: 7,
    skills: { fixed: ['nature'], choose: 3, list: ['arcana', 'athletics', 'diplomacy', 'endurance', 'heal', 'history', 'insight', 'nature', 'perception'] },
    features: [
      { name: 'Balance of Nature', desc: 'Among your at-will attack powers you must have at least one beast form power and one that isn\'t.' },
      { name: 'Primal Aspect', desc: 'Primal Guardian lets you use Constitution for AC in light armor. Primal Predator gives you extra speed in light armor.' },
      { name: 'Ritual Casting', desc: 'You gain Ritual Caster as a bonus feat and know some rituals.' },
      { name: 'Wild Shape', desc: 'At will, as a minor action, change between your humanoid form and a beast form of your choice.' },
    ],
    options: [{ id: 'aspect', label: 'Primal Aspect', opts: { guardian: { name: 'Primal Guardian', desc: 'Use Constitution instead of Dexterity or Intelligence for AC while not in heavy armor.' }, predator: { name: 'Primal Predator', desc: '+1 speed while not in heavy armor.' } } }],
    bonusFeats: ['ritual-caster'],
  },
  invoker: {
    name: 'Invoker', src: 'PHB2', role: 'Controller', source: 'Divine', key: ['wis', 'con', 'int'],
    desc: 'A vessel of the gods\' raw power who hurls divine wrath at groups of enemies.',
    armor: ['cloth', 'leather', 'hide', 'chainmail'], shields: [], weapons: [SIMPLE_MELEE, SIMPLE_RANGED], implements: ['Rod', 'Staff'],
    def: { Fort: 1, Ref: 1, Will: 1 }, hp1: 10, hpLvl: 4, surges: 6,
    skills: { fixed: ['religion'], choose: 3, list: ['arcana', 'diplomacy', 'history', 'insight', 'intimidate', 'religion'] },
    features: [
      { name: 'Channel Divinity', desc: 'Once per encounter you can use one Channel Divinity power: rebuke undead or your covenant\'s power.' },
      { name: 'Divine Covenant', desc: 'Covenant of Preservation (Intelligence) protects and repositions allies. Covenant of Wrath (Constitution) boosts your defenses and damage when you attack.' },
      { name: 'Ritual Casting', desc: 'You gain Ritual Caster as a bonus feat and know some rituals.' },
    ],
    options: [{ id: 'covenant', label: 'Divine Covenant', opts: { preservation: { name: 'Covenant of Preservation', desc: 'Favors Intelligence.' }, wrath: { name: 'Covenant of Wrath', desc: 'Favors Constitution.' } } }],
    bonusFeats: ['ritual-caster'],
  },
  shaman: {
    name: 'Shaman', src: 'PHB2', role: 'Leader', source: 'Primal', key: ['wis', 'con', 'int'],
    desc: 'A healer who calls a spirit companion onto the battlefield; the spirit protects and empowers allies next to it.',
    armor: ['cloth', 'leather'], shields: [], weapons: [SIMPLE_MELEE, 'longspear'], implements: ['Totem'],
    def: { Fort: 1, Will: 1 }, hp1: 12, hpLvl: 5, surges: 7,
    skills: { fixed: ['nature'], choose: 3, list: ['arcana', 'athletics', 'endurance', 'heal', 'history', 'insight', 'nature', 'perception', 'religion'] },
    features: [
      { name: 'Companion Spirit', desc: 'You can call a spirit companion into a square near you. Many shaman powers work through it, and it grants a benefit to allies next to it depending on your spirit.' },
      { name: 'Healing Spirit', desc: 'Twice per encounter (three times from 16th level), a minor action lets an ally spend a healing surge, and an ally next to your spirit regains extra hit points.' },
      { name: 'Speak with Spirits', desc: 'Once per encounter, a minor action adds your Wisdom modifier to your next skill check.' },
      { name: 'Ritual Casting', desc: 'You gain Ritual Caster as a bonus feat and know some rituals.' },
    ],
    options: [{ id: 'spirit', label: 'Companion Spirit', opts: { bear: { name: 'Protector Spirit (bear)', desc: 'Favors Constitution. Allies next to the spirit regain extra hit points.' }, panther: { name: 'Stalker Spirit (panther)', desc: 'Favors Intelligence. Allies next to the spirit deal extra damage.' } } }],
    bonusFeats: ['ritual-caster'],
  },
  sorcerer: {
    name: 'Sorcerer', src: 'PHB2', role: 'Striker', source: 'Arcane', key: ['cha', 'str', 'dex'],
    desc: 'A spellcaster with magic in the blood, from a dragon ancestor or pure chaos, who deals heavy damage with Charisma-based spells.',
    armor: ['cloth'], shields: [], weapons: [SIMPLE_MELEE, SIMPLE_RANGED], implements: ['Dagger', 'Staff'],
    def: { Will: 2 }, hp1: 12, hpLvl: 5, surges: 6,
    skills: { fixed: ['arcana'], choose: 3, list: ['arcana', 'athletics', 'bluff', 'diplomacy', 'dungeoneering', 'endurance', 'history', 'insight', 'intimidate', 'nature'] },
    features: [
      { name: 'Spell Source', desc: 'Dragon Magic adds your Strength modifier to arcane power damage, lets you use Strength for AC in light armor and gives resistance to a chosen damage type. Wild Magic adds your Dexterity modifier to arcane power damage and gives random bonuses when you roll even or odd.' },
    ],
    options: [{ id: 'source', label: 'Spell Source', opts: { dragon: { name: 'Dragon Magic', desc: 'Favors Strength.' }, wild: { name: 'Wild Magic', desc: 'Favors Dexterity.' } } }],
  },
  warden: {
    name: 'Warden', src: 'PHB2', role: 'Defender', source: 'Primal', key: ['str', 'con', 'wis'],
    desc: 'A primal guardian who marks every enemy next to them each turn and punishes them with nature\'s wrath. Very durable, with lots of hit points.',
    armor: ['cloth', 'leather', 'hide'], shields: ['light', 'heavy'], weapons: [SIMPLE_MELEE, MILITARY_MELEE, SIMPLE_RANGED], implements: [],
    def: { Fort: 1, Will: 1 }, hp1: 17, hpLvl: 7, surges: 9,
    skills: { fixed: ['nature'], choose: 3, list: ['athletics', 'dungeoneering', 'endurance', 'heal', 'intimidate', 'nature', 'perception'] },
    features: [
      { name: 'Font of Life', desc: 'At the start of your turn, you can make a saving throw against one effect that a save can end.' },
      { name: 'Guardian Might', desc: 'Earthstrength (Constitution) gives you extra AC when you use your second wind. Wildblood (Wisdom) hinders enemies you mark when you use your second wind.' },
      { name: 'Nature\'s Wrath', desc: 'Once per turn, as a free action, mark each enemy adjacent to you until the end of your next turn.' },
      { name: 'Warden\'s Fury and Warden\'s Grasp', desc: 'Encounter powers that punish marked enemies who attack your allies: Fury attacks them, Grasp slides and slows them.' },
    ],
    options: [{ id: 'might', label: 'Guardian Might', opts: { earth: { name: 'Earthstrength', desc: 'Favors Constitution.' }, wild: { name: 'Wildblood', desc: 'Favors Wisdom.' } } }],
  },

  custom: {
    name: 'Custom class', src: 'Custom', role: 'Any', source: 'Any', key: [],
    desc: 'Build any other class (Essentials, Player\'s Handbook 3, hybrid, homebrew). Set the name, hit points, defenses, skills and proficiencies yourself, then add powers from the 4e Database.',
    armor: [], shields: [], weapons: [], implements: [], def: {}, hp1: 12, hpLvl: 5, surges: 7,
    skills: { choose: 4, list: Object.keys(D4.SKILLS) },
    features: [], custom: true,
  },
};

/* Class feature powers */
D4.addPowers([
  { cls: 'cleric', n: 'Healing Word', u: 'enc', ty: 'feature', k: 'Divine, Healing', a: 'minor', r: 'Close burst 5 (10 at 11th level, 15 at 21st level)', t: 'You or one ally in the burst',
    eff: 'The target can spend a healing surge and regain an additional 1d6 hit points. The extra healing becomes 2d6 at 6th level, 3d6 at 11th, 4d6 at 16th, 5d6 at 21st and 6d6 at 26th. Healer\'s Lore adds your Wisdom modifier.',
    spec: 'You can use this power twice per encounter, but only once per round. From 16th level, three times per encounter.',
    s: 'Minor action: an ally spends a healing surge and regains extra hit points.', heal: 'word', uses: c => c.lvl >= 16 ? 3 : 2 },
  { cls: 'cleric', n: 'Divine Fortune', u: 'enc', ty: 'feature', k: 'Divine, Channel Divinity', a: 'free', r: 'Personal',
    eff: 'You gain a +1 bonus to your next attack roll or saving throw before the end of your next turn.',
    spec: 'You can use only one Channel Divinity power per encounter.', s: 'Channel Divinity: +1 to your next attack roll or saving throw.', cd: true },
  { cls: 'cleric', n: 'Turn Undead', u: 'enc', ty: 'feature', k: 'Divine, Implement, Radiant, Channel Divinity', a: 'std', r: 'Close burst 2 (5 at 11th level, 8 at 21st level)', t: 'Each undead creature in the burst',
    atk: 'Wisdom vs. Will',
    hit: '1d10 + Wisdom modifier radiant damage, and you push the target a number of squares equal to 3 + your Charisma modifier. The target is immobilized until the end of your next turn.',
    miss: 'Half damage, and the target is not pushed or immobilized.',
    more: [['Scaling', 'The damage becomes 2d10 at 5th level, 3d10 at 11th, 4d10 at 15th, 5d10 at 21st and 6d10 at 25th.']],
    spec: 'You can use only one Channel Divinity power per encounter.', s: 'Channel Divinity: blast nearby undead with radiant damage, push them and hold them in place.',
    x: 'wis/Will/1d10+wis', cd: true },

  { cls: 'fighter', n: 'Combat Challenge', u: 'aw', ty: 'feature', k: 'Martial', a: 'int', r: 'Melee weapon', trig: 'An enemy marked by you and adjacent to you shifts or makes an attack that doesn\'t include you.',
    eff: 'Make a melee basic attack against the triggering enemy.', spec: 'Whenever you attack an enemy, hit or miss, you can mark it until the end of your next turn.',
    s: 'Mark every enemy you attack; punish marked enemies that shift or ignore you with a free melee basic attack.', x: 'str/AC/1W+str', x21: '2W+str' },

  { cls: 'paladin', n: 'Divine Challenge', u: 'aw', ty: 'feature', k: 'Divine, Radiant', a: 'minor', r: 'Close burst 5', t: 'One enemy in the burst',
    eff: 'You mark the target. It stays marked until you use this power on another target, or until you fail to engage it (attack it or end your turn adjacent to it) on one of your turns. While marked, the first time each turn the target makes an attack that doesn\'t include you, it takes radiant damage equal to 3 + your Charisma modifier. This becomes 6 + Charisma modifier at 11th level and 9 + Charisma modifier at 21st level.',
    spec: 'You can use this power only once per turn. The radiant damage can\'t be dealt more than once per turn. A creature can be marked by only one creature at a time.',
    s: 'Mark an enemy; it takes radiant damage the first time each turn it attacks someone else.', dc: true },
  { cls: 'paladin', n: 'Lay on Hands', u: 'aw', ty: 'feature', k: 'Divine, Healing', a: 'minor', r: 'Melee touch', t: 'One creature', req: 'You must have at least one healing surge remaining.',
    eff: 'You spend a healing surge but regain no hit points. Instead, the target regains hit points as if it had spent a healing surge.',
    spec: 'You can use this power a number of times per day equal to your Wisdom modifier (minimum 1), but only once per round.',
    s: 'Spend your own healing surge to heal an ally you touch.', uses: c => Math.max(1, c.mod.wis), usesPer: 'day' },
  { cls: 'paladin', n: 'Divine Mettle', u: 'enc', ty: 'feature', k: 'Divine, Channel Divinity', a: 'minor', r: 'Close burst 10', t: 'One creature in the burst',
    eff: 'The target makes a saving throw with a bonus equal to your Charisma modifier.', spec: 'You can use only one Channel Divinity power per encounter.',
    s: 'Channel Divinity: an ally makes a saving throw with a bonus.', cd: true },
  { cls: 'paladin', n: 'Divine Strength', u: 'enc', ty: 'feature', k: 'Divine, Channel Divinity', a: 'minor', r: 'Personal',
    eff: 'Apply your Strength modifier as extra damage on your next attack this turn.', spec: 'You can use only one Channel Divinity power per encounter.',
    s: 'Channel Divinity: add your Strength modifier to your next damage roll this turn.', cd: true },

  { cls: 'ranger', n: 'Hunter\'s Quarry', u: 'aw', ty: 'feature', k: 'Martial', a: 'minor', r: 'Personal', t: 'The enemy nearest to you that you can see',
    eff: 'The target becomes your quarry until the end of the encounter, until it is defeated, or until you choose a new quarry. Once per round, you deal extra damage to your quarry when you hit it: 1d6 at 1st level, 2d6 at 11th, 3d6 at 21st. With several attacks in a round, choose which one gets the extra damage after rolling.',
    spec: 'You can use this power once per turn.', s: 'Designate the nearest enemy as your quarry: +1d6 damage to it once per round.', extra: c => (c.tier) + 'd6' },

  { cls: 'rogue', n: 'Sneak Attack', u: 'aw', ty: 'feature', k: 'Martial', a: 'no', r: 'Personal', req: 'You have combat advantage against the target and use a light blade, crossbow or sling.',
    eff: 'Once per round, when you hit, deal extra damage: 2d6 at 1st level, 3d6 at 11th, 5d6 at 21st. Brutal Scoundrel adds your Strength modifier. You decide after rolling damage.',
    s: 'Once per round, +2d6 damage when you hit with combat advantage.', extra: c => ({ 1: '2d6', 2: '3d6', 3: '5d6' })[c.tier] + (c.ch.clsOpt.tactics === 'brutal' ? ' + ' + c.mod.str : '') },

  { cls: 'warlock', n: 'Eldritch Blast', l: 1, u: 'aw', ty: 'atk', k: 'Arcane, Implement', a: 'std', r: 'Ranged 10', t: 'One creature',
    atk: 'Charisma vs. Reflex or Constitution vs. Reflex', hit: '1d10 + Charisma modifier damage, or 1d10 + Constitution modifier damage if you used Constitution.',
    l21: '2d10 + Charisma or Constitution modifier damage.', spec: 'This power counts as a ranged basic attack. When a power lets you make a ranged basic attack, you can use this power.',
    s: 'Your signature ranged spell: 1d10 + Charisma or Constitution.', x: 'cha|con/Ref/1d10+cha|con', x21: '2d10+cha|con' },
  { cls: 'warlock', n: 'Warlock\'s Curse', u: 'aw', ty: 'feature', k: 'Arcane', a: 'minor', r: 'Personal', t: 'The enemy nearest to you that you can see',
    eff: 'The target is cursed until the end of the encounter or until it drops to 0 hit points. Once per round, when you damage a cursed enemy, deal extra damage: 1d6 at 1st level, 2d6 at 11th, 3d6 at 21st. Your pact boon triggers when a cursed enemy drops to 0 hit points.',
    spec: 'You can use this power once per turn. You can\'t curse a creature that is already cursed.', s: 'Curse the nearest enemy: +1d6 damage to it once per round.', extra: c => c.tier + 'd6' },

  { cls: 'warlord', n: 'Inspiring Word', u: 'enc', ty: 'feature', k: 'Martial, Healing', a: 'minor', r: 'Close burst 5 (10 at 11th level, 15 at 21st level)', t: 'You or one ally in the burst',
    eff: 'The target can spend a healing surge and regain an additional 1d6 hit points. The extra healing becomes 2d6 at 6th level, 3d6 at 11th, 4d6 at 16th, 5d6 at 21st and 6d6 at 26th.',
    spec: 'You can use this power twice per encounter, but only once per round. From 16th level, three times per encounter.',
    s: 'Minor action: an ally spends a healing surge and regains extra hit points.', heal: 'word', uses: c => c.lvl >= 16 ? 3 : 2 },

  { cls: 'wizard', n: 'Ghost Sound', l: 1, u: 'aw', ty: 'util', k: 'Arcane, Illusion', a: 'std', r: 'Ranged 10', t: 'One object or unoccupied square',
    eff: 'A sound comes from the target: anything from a whisper to the noise of a fight, such as clashing swords or footsteps. If you whisper, only creatures next to the target hear you.',
    s: 'Cantrip: create an illusory sound.', cantrip: true },
  { cls: 'wizard', n: 'Light', l: 1, u: 'aw', ty: 'util', k: 'Arcane', a: 'minor', r: 'Ranged 5', t: 'One object not carried by another creature',
    eff: 'The target sheds bright light out to 4 squares until the end of the encounter, until you use this power again, or until you put it out (free action).',
    s: 'Cantrip: make an object glow like a torch.', cantrip: true },
  { cls: 'wizard', n: 'Mage Hand', l: 1, u: 'aw', ty: 'util', k: 'Arcane, Conjuration', a: 'minor', r: 'Ranged 5',
    eff: 'You conjure a floating hand in an unoccupied square. It can pick up, move or manipulate an object of up to 20 pounds and carry it up to 5 squares. As a move action you can move the hand 5 squares; as a minor action it can pick up or use a different object.',
    sus: 'Sustain Minor: The hand persists.', spec: 'You can have only one mage hand at a time.', s: 'Cantrip: a floating hand that moves light objects.', cantrip: true },
  { cls: 'wizard', n: 'Prestidigitation', l: 1, u: 'aw', ty: 'util', k: 'Arcane', a: 'std', r: 'Ranged 2',
    eff: 'Perform a minor trick for up to 1 hour: move 1 pound of material, make a harmless sensory effect (a shower of sparks, a puff of wind, faint music), color, clean or soil items, warm, cool or flavor 1 pound of nonliving material, make a small mark, or create a small illusion that lasts until the end of your next turn. You can have up to three effects active at once.',
    s: 'Cantrip: small magical tricks.', cantrip: true },
], { src: 'class' });

for (const k in D4.classes) D4.classes[k].id = k;
