/* Feats. Summaries written for this app.
   tier: H heroic (any level), P paragon (11th level+), E epic (21st level+).
   req: structured prerequisites the builder checks (abil, race, cls, train, feat, opt, prof, any).
   m: stat modifiers [target, value, bonus type, situational note, when]; target or value can be a function (c, choice).
   choice: what the feat asks you to pick (skill, classSkill, weaponGroup, weapon, implement, languages). */
'use strict';

D4.addFeats = function (list) {
  list.forEach(f => {
    f.id = f.id || f.n.toLowerCase().replace(/'/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    f.tier = f.tier || 'H';
    D4.feats[f.id] = f;
  });
};
const FEAT_TIER = c => c.tier; // +1 heroic, +2 paragon, +3 epic

D4.addFeats([
  /* General heroic feats */
  { n: 'Action Surge', cat: 'Racial', req: { race: ['human'] }, pre: 'Human',
    b: 'You gain a +3 bonus to attack rolls you make during any action you gained by spending an action point.', s: '+3 to attacks made with an action point action.' },
  { n: 'Alertness', b: 'You don\'t grant combat advantage to enemies during a surprise round (if you are awake), and you gain a +2 feat bonus to Perception checks.',
    s: '+2 Perception; not caught flat-footed in a surprise round.', m: [['skill:perception', 2, 'feat']] },
  { n: 'Armor Proficiency (Leather)', req: { any: [{ prof: 'cloth' }] }, pre: 'Training with cloth armor', b: 'You gain training with leather armor.', s: 'Wear leather armor.', grant: { armor: 'leather' } },
  { n: 'Armor Proficiency (Hide)', req: { abil: { str: 13, con: 13 }, prof: 'leather' }, pre: 'Str 13, Con 13, training with leather armor', b: 'You gain training with hide armor.', s: 'Wear hide armor.', grant: { armor: 'hide' } },
  { n: 'Armor Proficiency (Chainmail)', req: { abil: { str: 13, con: 13 }, any: [{ prof: 'leather' }, { prof: 'hide' }] }, pre: 'Str 13, Con 13, training with leather or hide armor', b: 'You gain training with chainmail.', s: 'Wear chainmail.', grant: { armor: 'chainmail' } },
  { n: 'Armor Proficiency (Scale)', req: { abil: { str: 13, con: 13 }, prof: 'chainmail' }, pre: 'Str 13, Con 13, training with chainmail', b: 'You gain training with scale armor.', s: 'Wear scale armor.', grant: { armor: 'scale' } },
  { n: 'Armor Proficiency (Plate)', req: { abil: { str: 15, con: 15 }, prof: 'scale' }, pre: 'Str 15, Con 15, training with scale armor', b: 'You gain training with plate armor.', s: 'Wear plate armor.', grant: { armor: 'plate' } },
  { n: 'Astral Fire', req: { abil: { dex: 13, cha: 13 } }, pre: 'Dex 13, Cha 13',
    b: 'You gain a +1 feat bonus to damage rolls when you use a power that has the fire or radiant keyword. The bonus is +2 at 11th level and +3 at 21st level.', s: '+1/+2/+3 damage with fire and radiant powers.',
    m: [['dmg', FEAT_TIER, 'feat', 'with fire or radiant powers']] },
  { n: 'Backstabber', cat: 'Class', req: { cls: ['rogue'] }, pre: 'Sneak Attack class feature', b: 'Your Sneak Attack extra damage dice are d8s instead of d6s.', s: 'Sneak Attack uses d8s.' },
  { n: 'Blade Opportunist', req: { abil: { str: 13, dex: 13 } }, pre: 'Str 13, Dex 13', b: 'You gain a +2 bonus to opportunity attack rolls with a light blade.', s: '+2 to opportunity attacks with light blades.', m: [['atk', 2, 'untyped', 'opportunity attacks with a light blade']] },
  { n: 'Burning Blizzard', req: { abil: { int: 13, wis: 13 } }, pre: 'Int 13, Wis 13',
    b: 'You gain a +1 feat bonus to damage rolls when you use a power that has the acid or cold keyword. The bonus is +2 at 11th level and +3 at 21st level.', s: '+1/+2/+3 damage with acid and cold powers.',
    m: [['dmg', FEAT_TIER, 'feat', 'with acid or cold powers']] },
  { n: 'Combat Reflexes', req: { abil: { dex: 13 } }, pre: 'Dex 13', b: 'You gain a +1 bonus to opportunity attack rolls.', s: '+1 to opportunity attacks.', m: [['atk', 1, 'untyped', 'opportunity attacks']] },
  { n: 'Dark Fury', req: { abil: { con: 13, wis: 13 } }, pre: 'Con 13, Wis 13',
    b: 'You gain a +1 feat bonus to damage rolls when you use a power that has the necrotic or psychic keyword. The bonus is +2 at 11th level and +3 at 21st level.', s: '+1/+2/+3 damage with necrotic and psychic powers.',
    m: [['dmg', FEAT_TIER, 'feat', 'with necrotic or psychic powers']] },
  { n: 'Defensive Mobility', b: 'You gain a +2 bonus to AC against opportunity attacks.', s: '+2 AC against opportunity attacks.', m: [['AC', 2, 'untyped', 'against opportunity attacks']] },
  { n: 'Dragonborn Frenzy', cat: 'Racial', req: { race: ['dragonborn'] }, pre: 'Dragonborn', b: 'While you are bloodied, you gain a +2 feat bonus to damage rolls.', s: '+2 damage while bloodied.', m: [['dmg', 2, 'feat', 'while bloodied']] },
  { n: 'Dragonborn Senses', cat: 'Racial', req: { race: ['dragonborn'] }, pre: 'Dragonborn', b: 'You gain low-light vision and a +1 feat bonus to Perception checks.', s: 'Low-light vision and +1 Perception.', m: [['skill:perception', 1, 'feat']], grant: { vision: 'Low-light' } },
  { n: 'Durable', b: 'Your number of healing surges increases by two.', s: '+2 healing surges per day.', m: [['surges', 2, 'untyped']] },
  { n: 'Dwarven Weapon Training', cat: 'Racial', req: { race: ['dwarf'] }, pre: 'Dwarf',
    b: 'You gain proficiency with all military and superior axes and hammers, and a +2 feat bonus to damage rolls with axes and hammers.', s: 'Axe and hammer proficiency and +2 damage with them.',
    m: [['dmg.group:Axe', 2, 'feat'], ['dmg.group:Hammer', 2, 'feat']], grant: { groups: ['Axe', 'Hammer'] } },
  { n: 'Eladrin Soldier', cat: 'Racial', req: { race: ['eladrin'] }, pre: 'Eladrin',
    b: 'You gain proficiency with all spears, and a +2 feat bonus to damage rolls with longswords and all spears.', s: 'Spear proficiency and +2 damage with longswords and spears.',
    m: [['dmg.weapon:longsword', 2, 'feat'], ['dmg.group:Spear', 2, 'feat']], grant: { groups: ['Spear'] } },
  { n: 'Elven Precision', cat: 'Racial', req: { race: ['elf'] }, pre: 'Elf', b: 'When you use elven accuracy, you gain a +2 bonus to the new attack roll.', s: '+2 to your elven accuracy reroll.' },
  { n: 'Enlarged Dragon Breath', cat: 'Racial', req: { race: ['dragonborn'] }, pre: 'Dragonborn', b: 'Your dragon breath is a close blast 5 instead of a close blast 3.', s: 'Dragon breath becomes a blast 5.' },
  { n: 'Far Shot', req: { abil: { dex: 13 } }, pre: 'Dex 13', b: 'When you use a projectile weapon (such as a bow, crossbow or sling), increase both its normal range and its long range by 5 squares.', s: '+5 squares of range with bows, crossbows and slings.' },
  { n: 'Far Throw', req: { abil: { str: 13 } }, pre: 'Str 13', b: 'When you use a thrown weapon, increase both its normal range and its long range by 2 squares.', s: '+2 squares of range with thrown weapons.' },
  { n: 'Fast Runner', req: { abil: { con: 13 } }, pre: 'Con 13', b: 'You gain a +2 bonus to speed when you charge or run.', s: '+2 speed when charging or running.', m: [['speed', 2, 'untyped', 'when you charge or run']] },
  { n: 'Great Fortitude', b: 'You gain a +2 feat bonus to Fortitude. It increases to +3 at 11th level and +4 at 21st level.', s: '+2 Fortitude (more at higher tiers).', m: [['Fort', c => c.tier + 1, 'feat']] },
  { n: 'Healing Hands', cat: 'Class', req: { cls: ['paladin'] }, pre: 'Lay on Hands class feature', b: 'When you use lay on hands, the target regains additional hit points equal to your Charisma modifier.', s: 'Lay on hands heals more.' },
  { n: 'Hellfire Blood', cat: 'Racial', req: { race: ['tiefling'] }, pre: 'Tiefling', b: 'You gain a +1 feat bonus to attack rolls and damage rolls when you use a power that has the fire or fear keyword.', s: '+1 to attack and damage with fire and fear powers.',
    m: [['atk', 1, 'feat', 'with fire or fear powers'], ['dmg', 1, 'feat', 'with fire or fear powers']] },
  { n: 'Human Perseverance', cat: 'Racial', req: { race: ['human'] }, pre: 'Human', b: 'You gain a +1 feat bonus to saving throws.', s: '+1 to saving throws.', m: [['save', 1, 'feat']] },
  { n: 'Improved Dark One\'s Blessing', cat: 'Class', req: { cls: ['warlock'], opt: { pact: 'infernal' } }, pre: 'Infernal pact', b: 'When your Dark One\'s Blessing pact boon triggers, you gain 3 more temporary hit points.', s: 'More temporary hit points from your infernal pact boon.' },
  { n: 'Improved Fate of the Void', cat: 'Class', req: { cls: ['warlock'], opt: { pact: 'star' } }, pre: 'Star pact', b: 'The bonus from your Fate of the Void pact boon increases (to +2 per trigger).', s: 'Bigger bonus from your star pact boon.' },
  { n: 'Improved Initiative', b: 'You gain a +4 feat bonus to initiative checks.', s: '+4 initiative.', m: [['init', 4, 'feat']] },
  { n: 'Improved Misty Step', cat: 'Class', req: { cls: ['warlock'], opt: { pact: 'fey' } }, pre: 'Fey pact', b: 'You teleport farther when your Misty Step pact boon triggers.', s: 'Longer teleport from your fey pact boon.' },
  { n: 'Inspired Recovery', cat: 'Class', req: { cls: ['warlord'], opt: { presence: 'inspiring' } }, pre: 'Inspiring Presence', b: 'When an ally who can see you spends an action point to take an extra action, that ally can also make a saving throw.', s: 'Allies who spend action points also get a saving throw.' },
  { n: 'Iron Will', b: 'You gain a +2 feat bonus to Will. It increases to +3 at 11th level and +4 at 21st level.', s: '+2 Will (more at higher tiers).', m: [['Will', c => c.tier + 1, 'feat']] },
  { n: 'Jack of All Trades', req: { abil: { int: 13 } }, pre: 'Int 13', b: 'You gain a +2 feat bonus to all untrained skill checks.', s: '+2 to untrained skill checks.', m: [['untrained', 2, 'feat']] },
  { n: 'Lethal Hunter', cat: 'Class', req: { cls: ['ranger'] }, pre: 'Hunter\'s Quarry class feature', b: 'Your Hunter\'s Quarry extra damage dice are d8s instead of d6s.', s: 'Hunter\'s Quarry uses d8s.' },
  { n: 'Lightning Reflexes', b: 'You gain a +2 feat bonus to Reflex. It increases to +3 at 11th level and +4 at 21st level.', s: '+2 Reflex (more at higher tiers).', m: [['Ref', c => c.tier + 1, 'feat']] },
  { n: 'Linguist', req: { abil: { int: 13 } }, pre: 'Int 13', b: 'Choose three languages. You can speak, read and write them fluently. You can take this feat more than once.', s: 'Learn three languages.', choice: { type: 'languages', count: 3, label: 'Three languages' }, repeat: true },
  { n: 'Long Jumper', req: { train: ['athletics'] }, pre: 'Trained in Athletics', b: 'You can make all long jumps as if you had a running start, and you gain a +1 feat bonus to Athletics checks.', s: 'Always jump as if running; +1 Athletics.', m: [['skill:athletics', 1, 'feat']] },
  { n: 'Lost in the Crowd', cat: 'Racial', req: { race: ['halfling'] }, pre: 'Halfling', b: 'You gain a +2 bonus to AC when you are adjacent to at least two enemies larger than you.', s: '+2 AC when next to two bigger enemies.', m: [['AC', 2, 'untyped', 'when adjacent to two or more larger enemies']] },
  { n: 'Mounted Combat', b: 'When you ride a creature, you gain access to its special mount abilities, and it can make Athletics, Acrobatics, Endurance and Stealth checks using your trained skills if better.', s: 'Fight effectively on a mount.' },
  { n: 'Nimble Blade', req: { abil: { dex: 15 } }, pre: 'Dex 15', b: 'When you attack with a light blade and have combat advantage, you gain a +1 bonus to the attack roll.', s: '+1 to hit with light blades when you have combat advantage.', m: [['atk', 1, 'untyped', 'with a light blade and combat advantage']] },
  { n: 'Potent Challenge', cat: 'Class', req: { cls: ['fighter'] }, pre: 'Combat Challenge class feature', b: 'When you make an attack because of Combat Challenge, add your Constitution modifier to the damage roll.', s: 'Combat Challenge attacks deal more damage.' },
  { n: 'Power Attack', req: { abil: { str: 15 } }, pre: 'Str 15',
    b: 'When making a melee attack, you can take a -2 penalty to the attack roll. If the attack hits, you gain a +2 bonus to the damage roll (+3 with a two-handed weapon). At 11th level the bonus is +4 (+6 two-handed); at 21st level, +6 (+9 two-handed).',
    s: 'Take -2 to hit for bonus melee damage.', m: [['dmg.melee', c => 2 * c.tier, 'untyped', 'if you take -2 to hit (more with two-handed weapons)']] },
  { n: 'Powerful Charge', req: { abil: { str: 13 } }, pre: 'Str 13', b: 'When you charge, you gain a +2 bonus to damage and a +2 bonus to bull rush attempts.', s: '+2 damage when charging.', m: [['dmg', 2, 'untyped', 'when charging']] },
  { n: 'Quick Draw', req: { abil: { dex: 13 } }, pre: 'Dex 13', b: 'You can draw a weapon (or an object stored in a belt pouch, bandolier or similar container) as part of the same action you use to attack with it. You also gain a +2 feat bonus to initiative checks.',
    s: 'Draw weapons for free; +2 initiative.', m: [['init', 2, 'feat']] },
  { n: 'Ritual Caster', req: { any: [{ train: ['arcana'] }, { train: ['religion'] }] }, pre: 'Trained in Arcana or Religion',
    b: 'You can master and perform rituals of your level or lower (see Rituals in the Player\'s Handbook). You need a ritual book and components.', s: 'Perform magical rituals.' },
  { n: 'Shield Proficiency (Light)', req: { abil: { str: 13 } }, pre: 'Str 13', b: 'You gain proficiency with light shields.', s: 'Use a light shield.', grant: { shield: 'light' } },
  { n: 'Shield Proficiency (Heavy)', req: { abil: { str: 15 }, prof: 'light-shield' }, pre: 'Str 15, Shield Proficiency (Light)', b: 'You gain proficiency with heavy shields.', s: 'Use a heavy shield.', grant: { shield: 'heavy' } },
  { n: 'Skill Focus', b: 'Choose a trained skill. You gain a +3 feat bonus to checks with that skill. You can take this feat more than once, choosing a different skill each time.',
    s: '+3 to one trained skill.', choice: { type: 'trainedSkill', label: 'Skill' }, m: [[(c, ch) => 'skill:' + ch, 3, 'feat']], repeat: true },
  { n: 'Skill Training', b: 'You gain training in one skill of your choice. You can take this feat more than once, choosing a different skill each time.',
    s: 'Become trained in one skill (+5).', choice: { type: 'skill', label: 'Skill' }, repeat: true },
  { n: 'Sure Climber', req: { train: ['athletics'] }, pre: 'Trained in Athletics', b: 'You can climb at your normal speed on any surface that doesn\'t need a DC higher than 15, and you gain a +1 feat bonus to Athletics checks to climb.', s: 'Climb at full speed.' },
  { n: 'Tactical Assault', cat: 'Class', req: { cls: ['warlord'], opt: { presence: 'tactical' } }, pre: 'Tactical Presence', b: 'When an ally uses an action point to make an attack and gains the bonus from your Tactical Presence, that ally also adds your Intelligence modifier to damage rolls for that attack.', s: 'Tactical Presence attacks also deal extra damage.' },
  { n: 'Toughness', b: 'You gain 5 additional hit points. At 11th level you gain 5 more, and 5 more at 21st level.', s: '+5 hit points per tier.', m: [['hp', c => 5 * c.tier, 'untyped']] },
  { n: 'Two-Weapon Defense', req: { abil: { dex: 13 }, feat: ['two-weapon-fighting'] }, pre: 'Dex 13, Two-Weapon Fighting',
    b: 'While you are holding a melee weapon in each hand, you gain a +1 shield bonus to AC and Reflex.', s: '+1 AC and Reflex with a weapon in each hand.',
    m: [['AC', 1, 'shield', null, c => c.dualWield], ['Ref', 1, 'shield', null, c => c.dualWield]] },
  { n: 'Two-Weapon Fighting', req: { abil: { dex: 13 } }, pre: 'Dex 13', b: 'While you are holding a melee weapon in each hand, you gain a +1 bonus to damage rolls with your main weapon.', s: '+1 damage with a weapon in each hand.',
    m: [['dmg.melee', 1, 'untyped', null, c => c.dualWield]] },
  { n: 'Weapon Focus', b: 'Choose a weapon group. You gain a +1 feat bonus to damage rolls with weapons of that group. At 11th level the bonus is +2, and at 21st level +3.',
    s: '+1/+2/+3 damage with one weapon group.', choice: { type: 'weaponGroup', label: 'Weapon group' }, m: [[(c, ch) => 'dmg.group:' + ch, FEAT_TIER, 'feat']], repeat: true },
  { n: 'Weapon Proficiency', b: 'You gain proficiency with a single weapon of your choice. You can take this feat more than once.',
    s: 'Gain proficiency with one weapon.', choice: { type: 'weapon', label: 'Weapon' }, repeat: true },

  /* Essentials-era defenses and expertise feats (Heroes of the Fallen Lands / Forgotten Kingdoms) */
  { n: 'Improved Defenses', src: 'HotFL', b: 'You gain a +1 feat bonus to Fortitude, Reflex and Will. At 11th level the bonus is +2, and at 21st level +3.',
    s: '+1/+2/+3 to Fortitude, Reflex and Will.', m: [['Fort', FEAT_TIER, 'feat'], ['Ref', FEAT_TIER, 'feat'], ['Will', FEAT_TIER, 'feat']] },
  { n: 'Weapon Expertise', src: 'HotFL', b: 'Choose a weapon group. You gain a +1 feat bonus to attack rolls with weapons of that group. At 11th level the bonus is +2, and at 21st level +3.',
    s: '+1/+2/+3 to hit with one weapon group.', choice: { type: 'weaponGroup', label: 'Weapon group' }, m: [[(c, ch) => 'atk.group:' + ch, FEAT_TIER, 'feat']], repeat: true },
  { n: 'Implement Expertise', src: 'HotFL', b: 'Choose an implement type. You gain a +1 feat bonus to attack rolls with that implement. At 11th level the bonus is +2, and at 21st level +3.',
    s: '+1/+2/+3 to hit with one implement type.', choice: { type: 'implement', label: 'Implement' }, m: [[(c, ch) => 'atk.imp:' + ch, FEAT_TIER, 'feat']], repeat: true },

  /* Multiclass feats (Player's Handbook). You can normally take only one class-specific multiclass feat. */
  { n: 'Arcane Initiate', cat: 'Multiclass', mc: 'wizard', req: { abil: { int: 13 } }, pre: 'Int 13',
    b: 'You gain training in Arcana. Choose a 1st-level wizard at-will attack spell; you can use it once per encounter. You can use wizard implements with wizard powers. You count as a wizard for paragon paths and multiclass feats.',
    s: 'Multiclass wizard: Arcana, and one wizard at-will spell per encounter.', grant: { skills: ['arcana'] } },
  { n: 'Initiate of the Faith', cat: 'Multiclass', mc: 'cleric', req: { abil: { wis: 13 } }, pre: 'Wis 13',
    b: 'You gain training in Religion. Once per day you can use the cleric\'s healing word power. You count as a cleric for paragon paths and multiclass feats.',
    s: 'Multiclass cleric: Religion, and healing word once per day.', grant: { skills: ['religion'] } },
  { n: 'Pact Initiate', cat: 'Multiclass', mc: 'warlock', req: { abil: { cha: 13 } }, pre: 'Cha 13',
    b: 'You gain training in one skill from the warlock\'s class skill list. You can use eldritch blast once per encounter. You can use rods and wands as implements for warlock powers. You count as a warlock for paragon paths and multiclass feats.',
    s: 'Multiclass warlock: a warlock skill, and eldritch blast once per encounter.', choice: { type: 'classSkill', cls: 'warlock', label: 'Warlock skill' } },
  { n: 'Sneak of Shadows', cat: 'Multiclass', mc: 'rogue', req: { abil: { dex: 13 } }, pre: 'Dex 13',
    b: 'You gain training in Thievery. Once per encounter, you can deal Sneak Attack extra damage when you hit an enemy you have combat advantage against. You count as a rogue for paragon paths and multiclass feats.',
    s: 'Multiclass rogue: Thievery, and Sneak Attack once per encounter.', grant: { skills: ['thievery'] } },
  { n: 'Soldier of the Faith', cat: 'Multiclass', mc: 'paladin', req: { abil: { str: 13, cha: 13 } }, pre: 'Str 13, Cha 13',
    b: 'You gain training in one skill from the paladin\'s class skill list. Once per encounter you can use the paladin\'s divine challenge power. You count as a paladin for paragon paths and multiclass feats.',
    s: 'Multiclass paladin: a paladin skill, and divine challenge once per encounter.', choice: { type: 'classSkill', cls: 'paladin', label: 'Paladin skill' } },
  { n: 'Student of Battle', cat: 'Multiclass', mc: 'warlord', req: { abil: { str: 13, cha: 13 } }, pre: 'Str 13, Cha 13',
    b: 'You gain training in one skill from the warlord\'s class skill list. Once per day you can use the warlord\'s inspiring word power. You count as a warlord for paragon paths and multiclass feats.',
    s: 'Multiclass warlord: a warlord skill, and inspiring word once per day.', choice: { type: 'classSkill', cls: 'warlord', label: 'Warlord skill' } },
  { n: 'Student of the Sword', cat: 'Multiclass', mc: 'fighter', req: { abil: { str: 13 } }, pre: 'Str 13',
    b: 'You gain training in one skill from the fighter\'s class skill list. Once per encounter you can mark an enemy you attack, as a fighter does with Combat Challenge. You count as a fighter for paragon paths and multiclass feats.',
    s: 'Multiclass fighter: a fighter skill, and a fighter\'s mark once per encounter.', choice: { type: 'classSkill', cls: 'fighter', label: 'Fighter skill' } },
  { n: 'Warrior of the Wild', cat: 'Multiclass', mc: 'ranger', req: { any: [{ abil: { str: 13 } }, { abil: { dex: 13 } }] }, pre: 'Str 13 or Dex 13',
    b: 'You gain training in one skill from the ranger\'s class skill list. Once per encounter you can use Hunter\'s Quarry. You count as a ranger for paragon paths and multiclass feats.',
    s: 'Multiclass ranger: a ranger skill, and Hunter\'s Quarry once per encounter.', choice: { type: 'classSkill', cls: 'ranger', label: 'Ranger skill' } },
  { n: 'Novice Power', cat: 'Multiclass', req: { lvl: 4, mcFeat: true }, pre: '4th level, any class-specific multiclass feat',
    b: 'Swap one of your encounter attack powers of 3rd level or higher for an encounter attack power of the same level or lower from your multiclass class.', s: 'Swap an encounter attack power for one from your multiclass class.' },
  { n: 'Acolyte Power', cat: 'Multiclass', req: { lvl: 8, mcFeat: true }, pre: '8th level, any class-specific multiclass feat',
    b: 'Swap one of your utility powers of 6th level or higher for a utility power of the same level or lower from your multiclass class.', s: 'Swap a utility power for one from your multiclass class.' },
  { n: 'Adept Power', cat: 'Multiclass', req: { lvl: 10, mcFeat: true }, pre: '10th level, any class-specific multiclass feat',
    b: 'Swap one of your daily attack powers of 5th level or higher for a daily attack power of the same level or lower from your multiclass class.', s: 'Swap a daily attack power for one from your multiclass class.' },
  { tier: 'P', n: 'Paragon Multiclassing', cat: 'Multiclass', req: { lvl: 11, feat: ['novice-power', 'acolyte-power', 'adept-power'] }, pre: '11th level, Novice Power, Acolyte Power and Adept Power',
    b: 'Instead of a paragon path, you gain powers from your multiclass class: an encounter attack at 11th level, a utility power at 12th level and a daily attack at 20th level.', s: 'Take multiclass powers instead of a paragon path.' },

  /* Paragon tier */
  { tier: 'P', n: 'Action Recovery', b: 'Whenever you spend an action point to take an extra action, you also make a saving throw against each effect on you that a save can end.', s: 'Saving throws when you spend an action point.' },
  { tier: 'P', n: 'Armor Specialization (Chainmail)', req: { abil: { dex: 15 }, prof: 'chainmail' }, pre: 'Dex 15, training with chainmail', b: 'You gain a +1 bonus to AC while wearing chainmail, and its armor check penalty is reduced by 1.', s: '+1 AC in chainmail.', m: [['AC', 1, 'feat', null, c => c.armor && c.armor.type === 'chainmail']] },
  { tier: 'P', n: 'Armor Specialization (Hide)', req: { abil: { con: 15 }, prof: 'hide' }, pre: 'Con 15, training with hide armor', b: 'You gain a +1 bonus to AC while wearing hide armor, and its armor check penalty is reduced by 1.', s: '+1 AC in hide armor.', m: [['AC', 1, 'feat', null, c => c.armor && c.armor.type === 'hide']] },
  { tier: 'P', n: 'Armor Specialization (Leather)', req: { abil: { dex: 15 }, prof: 'leather' }, pre: 'Dex 15, training with leather armor', b: 'You gain a +1 bonus to AC while wearing leather armor.', s: '+1 AC in leather armor.', m: [['AC', 1, 'feat', null, c => c.armor && c.armor.type === 'leather']] },
  { tier: 'P', n: 'Armor Specialization (Plate)', req: { abil: { con: 15 }, prof: 'plate' }, pre: 'Con 15, training with plate armor', b: 'You gain a +1 bonus to AC while wearing plate armor, and its speed penalty is reduced.', s: '+1 AC in plate armor.', m: [['AC', 1, 'feat', null, c => c.armor && c.armor.type === 'plate']] },
  { tier: 'P', n: 'Armor Specialization (Scale)', req: { abil: { dex: 13 }, prof: 'scale' }, pre: 'Dex 13, training with scale armor', b: 'You gain a +1 bonus to AC while wearing scale armor, and you ignore its speed penalty.', s: '+1 AC in scale armor, no speed penalty.', m: [['AC', 1, 'feat', null, c => c.armor && c.armor.type === 'scale']] },
  { tier: 'P', n: 'Combat Anticipation', b: 'You gain a +1 feat bonus to all defenses against ranged, area and close attacks.', s: '+1 to defenses against ranged, area and close attacks.',
    m: [['AC', 1, 'feat', 'against ranged, area and close attacks'], ['Fort', 1, 'feat', 'against ranged, area and close attacks'], ['Ref', 1, 'feat', 'against ranged, area and close attacks'], ['Will', 1, 'feat', 'against ranged, area and close attacks']] },
  { tier: 'P', n: 'Danger Sense', b: 'When you roll initiative, roll twice and use the higher result.', s: 'Roll initiative twice.' },
  { tier: 'P', n: 'Defensive Advantage', req: { abil: { dex: 17 } }, pre: 'Dex 17', b: 'When you have combat advantage against an enemy, you gain a +2 bonus to AC against that enemy\'s attacks.', s: '+2 AC against enemies you have combat advantage against.', m: [['AC', 2, 'untyped', 'against enemies you have combat advantage against']] },
  { tier: 'P', n: 'Fleet-Footed', b: 'You gain a +1 feat bonus to speed.', s: '+1 speed.', m: [['speed', 1, 'feat']] },
  { tier: 'P', n: 'Improved Second Wind', b: 'When you use your second wind, you regain an additional 5 hit points.', s: 'Second wind heals 5 more.' },
  { tier: 'P', n: 'Mettle', b: 'If an area or close attack misses you, you take no damage from it, even if it would deal damage on a miss.', s: 'Area and close attacks that miss you deal no damage.' },
  { tier: 'P', n: 'Point-Blank Shot', b: 'If you make a ranged attack against a target within 5 squares, you ignore cover and concealment (but not superior cover or total concealment).', s: 'Ignore cover when shooting at close range.' },
  { tier: 'P', n: 'Uncanny Dodge', b: 'Enemies don\'t gain combat advantage against you from flanking.', s: 'Can\'t be flanked for combat advantage.' },

  /* Epic tier */
  { tier: 'E', n: 'Devastating Critical', b: 'When you score a critical hit, you deal an extra 1d10 damage.', s: '+1d10 damage on critical hits.' },

  /* Channel Divinity feats (Player's Handbook). Require the Channel Divinity class feature and the listed deity. */
  ...[
    ['Armor of Bahamut', 'Bahamut', 'Turn a critical hit against an ally into a normal hit.'],
    ['Avandra\'s Rescue', 'Avandra', 'Shift into an ally\'s space and swap places with them.'],
    ['Corellon\'s Grace', 'Corellon', 'Move when an ally uses a power.'],
    ['Ioun\'s Poise', 'Ioun', 'Give an ally a big bonus to Will.'],
    ['Kord\'s Favor', 'Kord', 'Heal an ally when you score a critical hit.'],
    ['Melora\'s Tide', 'Melora', 'Give a bloodied ally regeneration.'],
    ['Moradin\'s Resolve', 'Moradin', 'Gain a bonus against larger enemies.'],
    ['Pelor\'s Radiance', 'Pelor', 'Burn and stun nearby undead.'],
    ['Raven Queen\'s Blessing', 'The Raven Queen', 'Let an ally spend a healing surge when you drop an enemy.'],
    ['Sehanine\'s Reversal', 'Sehanine', 'Gain combat advantage against an enemy that attacked you.'],
  ].map(([n, god, s]) => ({ n, cat: 'Divinity', req: { anyCls: ['cleric', 'paladin', 'avenger', 'invoker'] }, pre: 'Channel Divinity class feature, must worship ' + god,
    b: 'You gain a Channel Divinity power granted by ' + god + ' (you can still use only one Channel Divinity power per encounter). ' + s + ' See the full text for the power.', s })),
]);
