/* Wizard spells (Player's Handbook), heroic tier. Summaries written for this app.
   See powers-fighter.js for the field guide. */
'use strict';

D4.addPowers([
  /* At-will 1 */
  { n: 'Cloud of Daggers', l: 1, u: 'aw', k: 'Arcane, Force, Implement', a: 'std', r: 'Area 1 square within 10', t: 'Each creature in the square',
    atk: 'Intelligence vs. Reflex', hit: '1d6 + Intelligence modifier force damage.',
    eff: 'The square fills with whirling daggers until the end of your next turn. Any creature that enters the square or starts its turn there takes force damage equal to your Wisdom modifier (minimum 1). You can dismiss the daggers as a minor action.',
    l21: '2d6 + Intelligence modifier force damage.', s: 'Hurt a creature and leave a square of blades that damages anyone who stays.', x: 'int/Ref/1d6+int', x21: '2d6+int' },
  { n: 'Magic Missile', l: 1, u: 'aw', k: 'Arcane, Force, Implement', a: 'std', r: 'Ranged 20', t: 'One creature',
    eff: 'The target takes 2 + your Intelligence modifier force damage. This becomes 3 + Intelligence modifier at 11th level and 5 + Intelligence modifier at 21st level.',
    spec: 'No attack roll: it always hits. It counts as a ranged basic attack. (This is the updated version. The original Player\'s Handbook version was Intelligence vs. Reflex for 2d4 + Intelligence modifier.)',
    s: 'A missile of force that never misses.', x: 'auto/-/2+int', x11: '3+int', x21: '5+int' },
  { n: 'Ray of Frost', l: 1, u: 'aw', k: 'Arcane, Cold, Implement', a: 'std', r: 'Ranged 10', t: 'One creature',
    atk: 'Intelligence vs. Fortitude', hit: '1d6 + Intelligence modifier cold damage, and the target is slowed until the end of your next turn.',
    l21: '2d6 + Intelligence modifier cold damage.', s: 'Damage and slow one enemy.', x: 'int/Fort/1d6+int', x21: '2d6+int' },
  { n: 'Scorching Burst', l: 1, u: 'aw', k: 'Arcane, Fire, Implement', a: 'std', r: 'Area burst 1 within 10', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Reflex', hit: '1d6 + Intelligence modifier fire damage.', l21: '2d6 + Intelligence modifier fire damage.',
    s: 'A small fireball that hits everything in a 3x3 area (allies too).', x: 'int/Ref/1d6+int', x21: '2d6+int' },
  { n: 'Thunderwave', l: 1, u: 'aw', k: 'Arcane, Implement, Thunder', a: 'std', r: 'Close blast 3', t: 'Each creature in the blast',
    atk: 'Intelligence vs. Fortitude', hit: '1d6 + Intelligence modifier thunder damage, and you push the target a number of squares equal to your Wisdom modifier.',
    l21: '2d6 + Intelligence modifier thunder damage.', s: 'Blast enemies next to you and push them away.', x: 'int/Fort/1d6+int', x21: '2d6+int' },

  /* Encounter 1 */
  { n: 'Burning Hands', l: 1, u: 'enc', k: 'Arcane, Fire, Implement', a: 'std', r: 'Close blast 5', t: 'Each creature in the blast',
    atk: 'Intelligence vs. Reflex', hit: '2d6 + Intelligence modifier fire damage.', miss: 'Half damage.', s: 'A big cone of fire.', x: 'int/Ref/2d6+int' },
  { n: 'Chill Strike', l: 1, u: 'enc', k: 'Arcane, Cold, Implement', a: 'std', r: 'Ranged 10', t: 'One creature',
    atk: 'Intelligence vs. Fortitude', hit: '2d8 + Intelligence modifier cold damage, and the target is dazed until the end of your next turn.',
    miss: 'Half damage, and the target is not dazed.', s: 'Damage and daze one enemy.', x: 'int/Fort/2d8+int' },
  { n: 'Force Orb', l: 1, u: 'enc', k: 'Arcane, Force, Implement', a: 'std', r: 'Ranged 20', t: 'One creature (primary target)',
    atk: 'Intelligence vs. Reflex', hit: '2d8 + Intelligence modifier force damage.',
    more: [['Secondary Target', 'Each enemy adjacent to the primary target'], ['Secondary Attack', 'Intelligence vs. Reflex. Hit: 1d10 + Intelligence modifier force damage.']],
    s: 'Hit one enemy hard and splash the enemies around it.', x: 'int/Ref/2d8+int' },
  { n: 'Icy Terrain', l: 1, u: 'enc', k: 'Arcane, Cold, Implement', a: 'std', r: 'Area burst 1 within 10', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Reflex', hit: '1d6 + Intelligence modifier cold damage, and the target is knocked prone.',
    eff: 'The area becomes difficult terrain until the end of your next turn. You can end this effect as a minor action.',
    s: 'Knock enemies prone and ice over the ground.', x: 'int/Ref/1d6+int' },
  { n: 'Ray of Enfeeblement', l: 1, u: 'enc', k: 'Arcane, Implement, Necrotic', a: 'std', r: 'Ranged 10', t: 'One creature',
    atk: 'Intelligence vs. Fortitude', hit: '1d10 + Intelligence modifier necrotic damage, and the target is weakened until the end of your next turn.',
    s: 'Weaken a big hitter so it deals half damage.', x: 'int/Fort/1d10+int' },

  /* Daily 1 */
  { n: 'Acid Arrow', l: 1, u: 'day', k: 'Acid, Arcane, Implement', a: 'std', r: 'Ranged 20', t: 'One creature (primary target)',
    atk: 'Intelligence vs. Reflex', hit: '2d8 + Intelligence modifier acid damage, and ongoing 5 acid damage (save ends).',
    more: [['Secondary Target', 'Each creature adjacent to the primary target'], ['Secondary Attack', 'Intelligence vs. Reflex. Hit: 1d8 + Intelligence modifier acid damage, and ongoing 5 acid damage (save ends).']],
    miss: 'Half damage, ongoing 2 acid damage to the primary target (save ends), and no secondary attack.',
    s: 'Acid that splashes nearby creatures and keeps burning.', x: 'int/Ref/2d8+int' },
  { n: 'Flaming Sphere', l: 1, u: 'day', k: 'Arcane, Conjuration, Fire, Implement', a: 'std', r: 'Ranged 10', t: 'One creature adjacent to the sphere',
    eff: 'You conjure a Medium flaming sphere in an unoccupied square within range, and it attacks an adjacent creature. Any creature that starts its turn next to the sphere takes 1d4 + Intelligence modifier fire damage. As a move action you can move the sphere up to 6 squares.',
    atk: 'Intelligence vs. Reflex', hit: '2d6 + Intelligence modifier fire damage.',
    sus: 'Sustain Minor: The sphere persists. As a standard action you can make another attack with it.',
    s: 'A rolling ball of fire you can move and attack with every turn.', x: 'int/Ref/2d6+int' },
  { n: 'Freezing Cloud', l: 1, u: 'day', k: 'Arcane, Cold, Implement', a: 'std', r: 'Area burst 2 within 10', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Fortitude', hit: '1d8 + Intelligence modifier cold damage.', miss: 'Half damage.',
    eff: 'The cloud lasts until the end of your next turn. A creature that enters the cloud or starts its turn there is attacked again. You can dismiss the cloud as a minor action.',
    s: 'A 5x5 cloud of freezing mist.', x: 'int/Fort/1d8+int' },
  { n: 'Sleep', l: 1, u: 'day', k: 'Arcane, Implement, Sleep', a: 'std', r: 'Area burst 2 within 20', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Will', hit: 'The target is slowed (save ends). If the target fails its first saving throw against this power, it becomes unconscious (save ends).',
    miss: 'The target is slowed (save ends).', s: 'Put a whole group of enemies to sleep.', x: 'int/Will/0' },

  /* Utility 2 */
  { n: 'Expeditious Retreat', l: 2, u: 'day', ty: 'util', k: 'Arcane', a: 'move', r: 'Personal', eff: 'You shift up to twice your speed.', s: 'Shift a long way.' },
  { n: 'Feather Fall', l: 2, u: 'day', ty: 'util', k: 'Arcane', a: 'int', r: 'Close burst 5', trig: 'You or a creature within 5 squares of you falls.', t: 'You or each creature in the burst',
    eff: 'Each target takes no damage from the fall and doesn\'t fall prone.', s: 'Save everyone from a fall.' },
  { n: 'Jump', l: 2, u: 'enc', ty: 'util', k: 'Arcane', a: 'move', r: 'Ranged 10', t: 'You or one creature',
    eff: 'The target makes an Athletics check to jump with a +10 power bonus. It doesn\'t need a running start, and the distance is not limited by its speed.', s: 'Make a magically long jump.' },
  { n: 'Shield', l: 2, u: 'enc', ty: 'util', k: 'Arcane, Force', a: 'int', r: 'Personal', trig: 'You are hit by an attack.',
    eff: 'You gain a +4 power bonus to AC and Reflex until the end of your next turn.', s: 'React to a hit with +4 to AC and Reflex (can turn the hit into a miss).' },

  /* Encounter 3 */
  { n: 'Color Spray', l: 3, u: 'enc', k: 'Arcane, Implement, Radiant', a: 'std', r: 'Close blast 5', t: 'Each creature in the blast',
    atk: 'Intelligence vs. Will', hit: '1d6 + Intelligence modifier radiant damage, and the target is dazed until the end of your next turn.',
    s: 'Daze everything in a big cone.', x: 'int/Will/1d6+int' },
  { n: 'Fire Shroud', l: 3, u: 'enc', k: 'Arcane, Fire, Implement', a: 'std', r: 'Close burst 3', t: 'Each enemy in the burst',
    atk: 'Intelligence vs. Fortitude', hit: '1d8 + Intelligence modifier fire damage.', s: 'Burn every enemy near you (not allies).', x: 'int/Fort/1d8+int' },
  { n: 'Icy Rays', l: 3, u: 'enc', k: 'Arcane, Cold, Implement', a: 'std', r: 'Ranged 10', t: 'One or two creatures',
    atk: 'Intelligence vs. Reflex, one attack per target', hit: '1d10 + Intelligence modifier cold damage, and the target is immobilized until the end of your next turn.',
    miss: 'The target is slowed until the end of your next turn.', s: 'Freeze two enemies in place.', x: 'int/Ref/1d10+int' },
  { n: 'Shock Sphere', l: 3, u: 'enc', k: 'Arcane, Implement, Lightning', a: 'std', r: 'Area burst 2 within 10', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Reflex', hit: '2d6 + Intelligence modifier lightning damage.', s: 'A 5x5 burst of lightning.', x: 'int/Ref/2d6+int' },

  /* Daily 5 */
  { n: 'Bigby\'s Icy Grasp', l: 5, u: 'day', k: 'Arcane, Cold, Conjuration, Implement', a: 'std', r: 'Ranged 20',
    s: 'Conjure a giant icy hand that grabs an enemy, holds it and keeps dealing cold damage while you sustain it.' },
  { n: 'Fireball', l: 5, u: 'day', k: 'Arcane, Fire, Implement', a: 'std', r: 'Area burst 3 within 20', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Reflex', hit: '4d6 + Intelligence modifier fire damage.', miss: 'Half damage.', s: 'The classic 7x7 explosion.', x: 'int/Ref/4d6+int' },
  { n: 'Stinking Cloud', l: 5, u: 'day', k: 'Arcane, Implement, Poison, Zone', a: 'std', r: 'Area burst 2 within 20', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Fortitude', hit: '1d10 + Intelligence modifier poison damage.',
    eff: 'The burst creates a zone of poisonous vapor that blocks line of sight until the end of your next turn. A creature that enters the zone or starts its turn there takes 1d10 + Intelligence modifier poison damage. As a move action you can move the zone up to 6 squares.',
    sus: 'Sustain Minor: The zone persists.', s: 'A movable cloud of poison that blocks sight.', x: 'int/Fort/1d10+int' },
  { n: 'Web', l: 5, u: 'day', k: 'Arcane, Implement, Zone', a: 'std', r: 'Area burst 2 within 10', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Reflex', hit: 'The target is immobilized (save ends).',
    eff: 'The burst creates a zone of webs that is difficult terrain until the end of the encounter and hinders creatures that enter it.',
    s: 'Sticky webs that immobilize enemies and clog an area.', x: 'int/Ref/0' },

  /* Utility 6 */
  { n: 'Dimension Door', l: 6, u: 'day', ty: 'util', k: 'Arcane, Teleportation', a: 'move', r: 'Personal', eff: 'You teleport up to 10 squares.', s: 'Teleport 10 squares.' },
  { n: 'Disguise Self', l: 6, u: 'day', ty: 'util', k: 'Arcane, Illusion', a: 'minor', r: 'Personal',
    eff: 'You look like a different humanoid of about your size until you end the effect or take an extended rest. Creatures can see through it with an Insight check opposed by your Bluff check.', s: 'Look like someone else.' },
  { n: 'Dispel Magic', l: 6, u: 'day', ty: 'util', k: 'Arcane, Implement', a: 'std', r: 'Ranged 10', t: 'One conjuration or zone',
    atk: 'Intelligence vs. the Will defense of the creator of the conjuration or zone', hit: 'The conjuration or zone is destroyed, and all its effects end, including those that normally last until a target saves.',
    s: 'End an enemy conjuration or zone.' },
  { n: 'Invisibility', l: 6, u: 'day', ty: 'util', k: 'Arcane, Illusion', a: 'std', r: 'Ranged 5', t: 'You or one creature',
    eff: 'The target is invisible until the end of your next turn. If it attacks, it becomes visible.', sus: 'Sustain Standard: The effect persists.', s: 'Turn yourself or an ally invisible.' },
  { n: 'Levitate', l: 6, u: 'day', ty: 'util', k: 'Arcane', a: 'move', r: 'Personal',
    eff: 'You rise vertically up to 4 squares and stay there, floating. While levitating you can move 1 square horizontally as a move action. If you end your turn more than 1 square above the ground you descend to 1 square above it.',
    sus: 'Sustain Move: You can move up or down 4 squares.', s: 'Float up and hover.' },
  { n: 'Wall of Fog', l: 6, u: 'day', ty: 'util', k: 'Arcane, Conjuration', a: 'std', r: 'Area wall 8 within 10',
    eff: 'You conjure a wall of fog up to 8 squares long and 4 squares high. It blocks line of sight but not movement, and lasts until the end of the encounter.', s: 'A wall of fog that blocks sight.' },

  /* Encounter 7 */
  { n: 'Fire Burst', l: 7, u: 'enc', k: 'Arcane, Fire, Implement', a: 'std', r: 'Area burst 2 within 20', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Reflex', hit: '3d6 + Intelligence modifier fire damage.', s: 'A 5x5 fireball.', x: 'int/Ref/3d6+int' },
  { n: 'Lightning Bolt', l: 7, u: 'enc', k: 'Arcane, Implement, Lightning', a: 'std', r: 'Ranged 10', t: 'One creature (primary target)',
    atk: 'Intelligence vs. Reflex', hit: '2d6 + Intelligence modifier lightning damage.', miss: 'Half damage.',
    more: [['Secondary Targets', 'Two other creatures within 10 squares of you'], ['Secondary Attack', 'Intelligence vs. Reflex. Hit: 1d6 + Intelligence modifier lightning damage. Miss: Half damage.']],
    s: 'Lightning that arcs from one enemy to two others.', x: 'int/Ref/2d6+int' },
  { n: 'Spectral Ram', l: 7, u: 'enc', k: 'Arcane, Force, Implement', a: 'std', r: 'Ranged 10', t: 'One creature',
    atk: 'Intelligence vs. Fortitude', hit: '2d10 + Intelligence modifier force damage, and you push the target 3 squares and knock it prone.',
    miss: 'Half damage, and the target is not pushed or knocked prone.', s: 'Smash an enemy back and down.', x: 'int/Fort/2d10+int' },
  { n: 'Winged Horde', l: 7, u: 'enc', k: 'Arcane, Implement', a: 'std', r: 'Area burst 1 within 10', t: 'Each enemy in the burst',
    atk: 'Intelligence vs. Will', hit: '1d6 + Intelligence modifier damage, and the target can\'t make opportunity attacks until the end of your next turn.',
    s: 'A swarm of bats that stops enemies making opportunity attacks.', x: 'int/Will/1d6+int' },

  /* Daily 9 */
  { n: 'Ice Storm', l: 9, u: 'day', k: 'Arcane, Cold, Implement, Zone', a: 'std', r: 'Area burst 3 within 20', t: 'Each creature in the burst',
    atk: 'Intelligence vs. Fortitude', hit: '2d8 + Intelligence modifier cold damage, and the target is immobilized (save ends).',
    s: 'A huge freezing storm that immobilizes enemies and leaves icy ground behind.', x: 'int/Fort/2d8+int' },
  { n: 'Lightning Serpent', l: 9, u: 'day', k: 'Arcane, Implement, Lightning, Poison', a: 'std', r: 'Ranged 10',
    s: 'A lightning snake that shocks one enemy and poisons it.' },
  { n: 'Mordenkainen\'s Sword', l: 9, u: 'day', k: 'Arcane, Conjuration, Force, Implement', a: 'std', r: 'Ranged 10',
    s: 'Conjure a floating sword of force that attacks each turn while you sustain it.' },
  { n: 'Wall of Fire', l: 9, u: 'day', k: 'Arcane, Conjuration, Fire, Implement', a: 'std', r: 'Area wall 8 within 10',
    s: 'A wall of flame that blocks sight and burns anything that enters it or stands next to it.' },

  /* Utility 10 */
  { n: 'Arcane Gate', l: 10, u: 'day', ty: 'util', k: 'Arcane, Teleportation', a: 'move', r: 'Ranged 20', s: 'Open two linked portals that creatures can step between.' },
  { n: 'Blur', l: 10, u: 'day', ty: 'util', k: 'Arcane, Illusion', a: 'minor', r: 'Personal', s: 'Your form blurs, making you hard to hit for the rest of the encounter.' },
  { n: 'Mirror Image', l: 10, u: 'day', ty: 'util', k: 'Arcane, Illusion', a: 'minor', r: 'Personal',
    eff: 'Three duplicate images of you appear, giving you a +6 power bonus to AC. Each time an attack misses you, one image disappears and the bonus drops by 2. When the bonus reaches 0, the images are gone. The images last up to 1 hour.',
    s: 'Illusory copies: +6 AC that shrinks by 2 each time you are missed.' },
  { n: 'Resistance', l: 10, u: 'day', ty: 'util', k: 'Arcane', a: 'minor', r: 'Ranged 10', s: 'Give yourself or an ally resistance to a damage type for the encounter.' },
], { cls: 'wizard', src: 'class', ty: 'atk' });
